// Code generated by hertz generator.

package main

import (
	"context"
	"net/http"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/kitex/tool/internal_pkg/log"
	"github.com/hertz-contrib/cors"
	prometheus "github.com/hertz-contrib/monitor-prometheus"
	"github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/xh-polaris/gopkg/hertz/middleware"
	logx "github.com/xh-polaris/gopkg/util/log"
	bizMiddleware "github.com/xh-polaris/psych-core-api/biz/adaptor/middleware"
	"github.com/xh-polaris/psych-core-api/biz/application"
	"github.com/xh-polaris/psych-core-api/pkg/httpx"
	"github.com/xh-polaris/psych-core-api/provider"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/contrib/propagators/b3"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	sdkresource "go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
)

func main() {
	provider.Init()

	ctx := context.Background()
	shutdown := InitTracer(ctx)
	defer shutdown()

	application.InitApplication()
	hlog.SetLogger(logx.NewHlogLogger())

	c := provider.Get().Config

	// 创建服务器追踪器
	tracer, cfg := tracing.NewServerTracer()
	// 创造hertz服务器实例
	h := server.New(
		server.WithHostPorts(c.ListenOn),
		server.WithTracer(prometheus.NewServerTracer(":9091", "/server/metrics")),
		tracer,
	)

	h.NoHijackConnPool = true

	// CORS 配置
	corsConf := cors.DefaultConfig()
	corsConf.AllowAllOrigins = true
	corsConf.AllowHeaders = []string{"*"}
	corsHandler := cors.New(corsConf)

	// 增加全局中间件链
	h.Use(corsHandler, tracing.ServerMiddleware(cfg), bizMiddleware.SetLogIDMW(), middleware.EnvironmentMiddleware, recovery.Recovery(), func(ctx context.Context, c *app.RequestContext) {
		ctx = httpx.InjectContext(ctx, c)
		c.Next(ctx)
	})

	// 注册路由
	register(h)
	log.Info("server start")

	h.Spin()
}

// InitTracer 初始化全局 OTel TracerProvider 和 TextMapPropagator。
// 返回 shutdown 函数，应在进程退出前调用以确保 span 全部 flush。
func InitTracer(ctx context.Context) (shutdown func()) {
	cfg := provider.Get().Config
	telemetry := cfg.Telemetry
	if telemetry.Disabled || telemetry.Endpoint == "" {
		hlog.Warnf("otel: tracing disabled (Telemetry.Endpoint not set or Disabled=true)")
		return func() {}
	}

	svcName := cfg.Name
	if svcName == "" {
		svcName = "psych-core-api"
	}

	// 使用 OTLP gRPC 导出器
	exporter, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(telemetry.Endpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		hlog.Warnf("otel: init otlp grpc exporter failed: %v", err)
		return func() {}
	}

	res, err := sdkresource.New(ctx,
		sdkresource.WithAttributes(
			semconv.ServiceName(svcName),
		),
	)
	if err != nil {
		hlog.Warnf("otel: init resource failed: %v", err)
		return func() {}
	}

	sampler := sdktrace.AlwaysSample()
	if telemetry.Sampler < 1.0 && telemetry.Sampler > 0 {
		sampler = sdktrace.ParentBased(sdktrace.TraceIDRatioBased(telemetry.Sampler))
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(res),
		sdktrace.WithSampler(sampler),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(
		propagation.TraceContext{},
		propagation.Baggage{},
		b3.New(), // 增加 B3 支持
	))

	// 设置 http 默认 Transport 开启 OTel
	http.DefaultTransport = otelhttp.NewTransport(http.DefaultTransport)

	return func() {
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := tp.Shutdown(shutdownCtx); err != nil {
			hlog.Errorf("otel: shutdown tracer provider: %v", err)
		}
	}
}
