// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/core_api"
)

// CreateConversation .
// @router /conversation/create [POST]
func CreateConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.CreateConversationResp)

	c.JSON(consts.StatusOK, resp)
}

// ListConversations .
// @router /conversation/list [POST]
func ListConversations(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListConversationsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.ListConversationsResp)

	c.JSON(consts.StatusOK, resp)
}

// GetConversation .
// @router /conversation/get [POST]
func GetConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetConversationResp)

	c.JSON(consts.StatusOK, resp)
}
