// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/basic"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/core_api"
)

// ConfigCreate .
// @router /config/create [POST]
func ConfigCreate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigCreateOrUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(basic.Response)

	c.JSON(consts.StatusOK, resp)
}

// ConfigUpdateInfo .
// @router /config/update_info [POST]
func ConfigUpdateInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigCreateOrUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(basic.Response)

	c.JSON(consts.StatusOK, resp)
}

// ConfigGetByUnitID .
// @router /config/get_by_unit_id [GET]
func ConfigGetByUnitID(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigGetByUnitIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.ConfigGetByUnitIdResp)

	c.JSON(consts.StatusOK, resp)
}
