// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/xh-polaris/psych-core-api/biz/adaptor/middleware"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/psych-core-api/pkg/httpx"
	"github.com/xh-polaris/psych-core-api/provider"
)

// ConfigCreate .
// @router /config/create [POST]
func ConfigCreate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigCreateOrUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	if c.IsAborted() {
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.ConfigCreate(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigUpdateInfo .
// @router /config/update_info [POST]
func ConfigUpdateInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigCreateOrUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	if c.IsAborted() {
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.ConfigUpdate(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigGetByUnitID .
// @router /config/get_by_unit_id [GET]
func ConfigGetByUnitID(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigGetByUnitIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	if c.IsAborted() {
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.ConfigGetByUnitID(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigGetCharacter .
// @router /config/get_character [GET]
func ConfigGetCharacter(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigGetCharacterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.ConfigGetCharacters(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigListVoice .
// @router /config/list_voice [GET]
func ConfigListVoice(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigListVoiceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.ConfigListVoice(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigAddCharacter .
// @router /config/add_character [POST]
func ConfigAddCharacter(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigAddCharacterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	if c.IsAborted() {
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.AddCharacter(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigUpdateCharacter .
// @router /config/update_character [POST]
func ConfigUpdateCharacter(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigUpdateCharacterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	if c.IsAborted() {
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.UpdateCharacter(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigDeleteCharacter .
// @router /config/delete_character [POST]
func ConfigDeleteCharacter(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigDeleteCharacterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	if c.IsAborted() {
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.DeleteCharacter(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}
