// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/xh-polaris/psych-core-api/biz/adaptor/middleware"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/psych-core-api/pkg/httpx"
	"github.com/xh-polaris/psych-core-api/provider"
)

// ConfigCreate .
// @router /config/create [POST]
func ConfigCreate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigCreateOrUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.ConfigService.ConfigCreate(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigUpdateInfo .
// @router /config/update_info [POST]
func ConfigUpdateInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigCreateOrUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.ConfigService.ConfigUpdateInfo(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ConfigGetByUnitID .
// @router /config/get_by_unit_id [GET]
func ConfigGetByUnitID(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ConfigGetByUnitIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.ConfigService.ConfigGetByUnitID(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}
