// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/biz/adaptor/middleware"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/basic"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/psych-core-api/pkg/httpx"
	"github.com/xh-polaris/psych-core-api/provider"
)

type archiveConversationReq struct {
	ConversationId string `json:"conversationId" vd:"len($)>0"`
}

type archiveConversationResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type getConvByDateReq struct {
	PaginationOptions *basic.PaginationOptions `json:"paginationOptions"`
	Date              string                   `json:"date"`
	UserId            string                   `json:"userId"`
	CharacterId       string                   `json:"characterId"`
}

// CreateConversation .
// @router /conversation/create [POST]
func CreateConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.ConversationService.CreateConversation(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ListConversations .
// @router /conversation/list [POST]
func ListConversations(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListConversationsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.ConversationService.ListConversations(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// GetSingleConv .
// @router /conversation/get_single [POST]
func GetSingleConv(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetSingleConvReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.ConversationService.GetSingleConv(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// ArchiveConversation 将已结束的学生会话整理并归档到历史记录。
func ArchiveConversation(ctx context.Context, c *app.RequestContext) {
	var req archiveConversationReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	err := p.ConversationService.ArchiveConversation(ctx, req.ConversationId)
	httpx.PostProcess(ctx, c, &req, &archiveConversationResp{Code: 0, Msg: "success"}, err)
}

// GetConvByDate .
// @router /conversation/get_by_date [POST]
func GetConvByDate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req getConvByDateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.ConversationService.GetConvByDate(ctx, &core_api.GetConvByDateReq{
		PaginationOptions: req.PaginationOptions,
		Date:              req.Date,
		UserId:            req.UserId,
	}, req.CharacterId)
	httpx.PostProcess(ctx, c, &req, resp, err)
}
