// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/provider"
	"github.com/xh-polaris/psych-idl/kitex_gen/core_api"
	"github.com/xh-polaris/psych-pkg/httpx"
)

// UserSignIn .
// @router /user/sign_in [POST]
func UserSignIn(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UserSignInReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.AuthService.UserSignIn(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// UserGetInfo .
// @router /user/info [GET]
func UserGetInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UserGetInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.AuthService.UserGetInfo(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}
