// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/biz/adaptor/middleware"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/psych-core-api/pkg/httpx"
	"github.com/xh-polaris/psych-core-api/provider"
)

// DashboardGetDataOverview .
// @router /dashboard/overview [POST]
func DashboardGetDataOverview(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardGetDataOverviewReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardGetDataOverview(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardGetDataTrend .
// @router /dashboard/trend [POST]
func DashboardGetDataTrend(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardGetDataTrendReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardGetDataTrend(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardListUnits .
// @router /dashboard/units [POST]
func DashboardListUnits(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardListUnitsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardListUnits(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardGetPsychTrend .
// @router /dashboard/psych_trend [POST]
func DashboardGetPsychTrend(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardGetPsychTrendReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardGetPsychTrend(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardGetAlarmOverview .
// @router /dashboard/alarm_overview [POST]
func DashboardGetAlarmOverview(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardGetAlarmOverviewReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.AlarmService.Overview(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardListAlarmRecords .
// @router /dashboard/alarm_records [POST]
func DashboardListAlarmRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardListAlarmRecordsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.AlarmService.ListRecords(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardUpdateAlarm .
// @router /dashboard/update_alarm [POST]
func DashboardUpdateAlarm(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardUpdateAlarmReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.AlarmService.UpdateAlarm(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardListClasses .
// @router /dashboard/classes [POST]
func DashboardListClasses(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardListClassesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardListClasses(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardListUsers .
// @router /dashboard/users [POST]
func DashboardListUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardListUsersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardListUsers(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardUserConvRecords .
// @router /dashboard/user_conversation_records [POST]
func DashboardUserConvRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardUserConvRecordsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardUserConvRecords(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardUnitConvRecords .
// @router /dashboard/unit_conversation_records [POST]
func DashboardUnitConvRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardUnitConvRecordsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardUnitConvRecords(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// DashboardGetReport .
// @router /dashboard/get_report [POST]
func DashboardGetReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DashboardGetReportReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	middleware.StoreToken(ctx, c, &req)
	p := provider.Get()
	resp, err := p.DashboardService.DashboardGetReport(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}
