// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/psych-core-api/biz/cst"
	"github.com/xh-polaris/psych-core-api/pkg/httpx"
	"github.com/xh-polaris/psych-core-api/provider"
)

// UnitGetInfo .
// @router /unit/get_info [GET]
func UnitGetInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UnitGetInfoReq
	req.UnitId = c.Query(cst.QueryUnitID)

	p := provider.Get()
	resp, err := p.UnitService.UnitGetInfo(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// UnitUpdateInfo .
// @router /unit/update_info [POST]
func UnitUpdateInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UnitUpdateInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UnitService.UnitUpdateInfo(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// UnitGetByURI .
// @router /unit/get_by_uri [POST]
func UnitGetByURI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UnitGetByURIReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UnitService.UnitFindByURI(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// CreateUnit .
// @router /unit/create [POST]
func CreateUnit(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateUnitReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UnitService.UnitCreate(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}
