// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/psych-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/psych-core-api/biz/cst"
	"github.com/xh-polaris/psych-core-api/pkg/httpx"
	"github.com/xh-polaris/psych-core-api/provider"
)

// UserSignIn .
// @router /user/sign_in [POST]
func UserSignIn(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UserSignInReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.UserSignIn(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// UserGetInfo .
// @router /user/get_info [GET]
func UserGetInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UserGetInfoReq
	req.UserId = c.Query(cst.QueryUserID)

	p := provider.Get()
	resp, err := p.UserService.UserGetInfo(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// UserUpdateInfo .
// @router /user/update_info [POST]
func UserUpdateInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UserUpdateInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.UserUpdateInfo(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// UserUpdatePassword .
// @router /user/update_password [POST]
func UserUpdatePassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UserUpdatePasswordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.UserUpdatePassword(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// CreateUser .
// @router /user/create [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.CreateUser(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}

// SendVerifyCode .
// @router /user/send_verify_code [POST]
func SendVerifyCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SendVerifyCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.SendVerifyCode(ctx, &req)
	httpx.PostProcess(ctx, c, &req, resp, err)
}
