// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: core_api/common.proto

package core_api

import (
	_ "github.com/xh-polaris/psych-core-api/biz/application/dto/basic"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 可返回给前端的用户信息
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" form:"id" json:"id" query:"id"`
	Phone      string `protobuf:"bytes,2,opt,name=phone,proto3" form:"phone" json:"phone" query:"phone"`
	Name       string `protobuf:"bytes,4,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Birth      string `protobuf:"bytes,5,opt,name=birth,proto3" form:"birth" json:"birth" query:"birth"`
	Gender     int32  `protobuf:"varint,6,opt,name=gender,proto3" form:"gender" json:"gender" query:"gender"`
	Status     int32  `protobuf:"varint,7,opt,name=status,proto3" form:"status" json:"status" query:"status"`
	CreateTime int64  `protobuf:"varint,8,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
	UpdateTime int64  `protobuf:"varint,9,opt,name=updateTime,proto3" form:"updateTime" json:"updateTime" query:"updateTime"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetBirth() string {
	if x != nil {
		return x.Birth
	}
	return ""
}

func (x *User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *User) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type UserSignInReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId     string `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
	AuthType   int32  `protobuf:"varint,2,opt,name=authType,proto3" form:"authType" json:"authType" query:"authType"`
	AuthId     string `protobuf:"bytes,3,opt,name=authId,proto3" form:"authId" json:"authId" query:"authId"`
	VerifyCode string `protobuf:"bytes,4,opt,name=verifyCode,proto3" form:"verifyCode" json:"verifyCode" query:"verifyCode"`
}

func (x *UserSignInReq) Reset() {
	*x = UserSignInReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignInReq) ProtoMessage() {}

func (x *UserSignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignInReq.ProtoReflect.Descriptor instead.
func (*UserSignInReq) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *UserSignInReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UserSignInReq) GetAuthType() int32 {
	if x != nil {
		return x.AuthType
	}
	return 0
}

func (x *UserSignInReq) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *UserSignInReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type UserSignInResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId    string  `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
	UserId    string  `protobuf:"bytes,2,opt,name=userId,proto3" form:"userId" json:"userId" query:"userId"`
	StudentId *string `protobuf:"bytes,3,opt,name=studentId,proto3,oneof" form:"studentId" json:"studentId" query:"studentId"`
	Strong    bool    `protobuf:"varint,4,opt,name=strong,proto3" form:"strong" json:"strong" query:"strong"`
	Token     string  `protobuf:"bytes,5,opt,name=token,proto3" form:"token" json:"token" query:"token"`
	Code      int32   `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg       string  `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *UserSignInResp) Reset() {
	*x = UserSignInResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignInResp) ProtoMessage() {}

func (x *UserSignInResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignInResp.ProtoReflect.Descriptor instead.
func (*UserSignInResp) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{2}
}

func (x *UserSignInResp) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UserSignInResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSignInResp) GetStudentId() string {
	if x != nil && x.StudentId != nil {
		return *x.StudentId
	}
	return ""
}

func (x *UserSignInResp) GetStrong() bool {
	if x != nil {
		return x.Strong
	}
	return false
}

func (x *UserSignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserSignInResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserSignInResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取信息
type UserGetInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserGetInfoReq) Reset() {
	*x = UserGetInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetInfoReq) ProtoMessage() {}

func (x *UserGetInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetInfoReq.ProtoReflect.Descriptor instead.
func (*UserGetInfoReq) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{3}
}

type UserGetInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User            `protobuf:"bytes,1,opt,name=user,proto3" form:"user" json:"user" query:"user"`
	Info *structpb.Struct `protobuf:"bytes,2,opt,name=info,proto3" form:"info" json:"info" query:"info"`
	Code int32            `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg  string           `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *UserGetInfoResp) Reset() {
	*x = UserGetInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetInfoResp) ProtoMessage() {}

func (x *UserGetInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetInfoResp.ProtoReflect.Descriptor instead.
func (*UserGetInfoResp) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{4}
}

func (x *UserGetInfoResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserGetInfoResp) GetInfo() *structpb.Struct {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UserGetInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserGetInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_core_api_common_proto protoreflect.FileDescriptor

var file_core_api_common_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x1a, 0x16, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69,
	0x72, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x69, 0x72, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x7b, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xc7, 0x01,
	0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x8a, 0x01, 0x0a, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x13,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2f,
	0x70, 0x73, 0x79, 0x63, 0x68, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x62,
	0x69, 0x7a, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64,
	0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_core_api_common_proto_rawDescOnce sync.Once
	file_core_api_common_proto_rawDescData = file_core_api_common_proto_rawDesc
)

func file_core_api_common_proto_rawDescGZIP() []byte {
	file_core_api_common_proto_rawDescOnce.Do(func() {
		file_core_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_common_proto_rawDescData)
	})
	return file_core_api_common_proto_rawDescData
}

var file_core_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_core_api_common_proto_goTypes = []interface{}{
	(*User)(nil),            // 0: core_api.User
	(*UserSignInReq)(nil),   // 1: core_api.UserSignInReq
	(*UserSignInResp)(nil),  // 2: core_api.UserSignInResp
	(*UserGetInfoReq)(nil),  // 3: core_api.UserGetInfoReq
	(*UserGetInfoResp)(nil), // 4: core_api.UserGetInfoResp
	(*structpb.Struct)(nil), // 5: google.protobuf.Struct
}
var file_core_api_common_proto_depIdxs = []int32{
	0, // 0: core_api.UserGetInfoResp.user:type_name -> core_api.User
	5, // 1: core_api.UserGetInfoResp.info:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func file_core_api_common_proto_init() {
	if File_core_api_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_api_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignInReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignInResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_api_common_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_api_common_proto_goTypes,
		DependencyIndexes: file_core_api_common_proto_depIdxs,
		MessageInfos:      file_core_api_common_proto_msgTypes,
	}.Build()
	File_core_api_common_proto = out.File
	file_core_api_common_proto_rawDesc = nil
	file_core_api_common_proto_goTypes = nil
	file_core_api_common_proto_depIdxs = nil
}
