// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: core_api/config.proto

package core_api

import (
	_ "github.com/xh-polaris/psych-core-api/biz/application/dto/basic"
	_ "github.com/xh-polaris/psych-core-api/biz/application/dto/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" form:"description" json:"description" query:"description"`
	Provider    string `protobuf:"bytes,3,opt,name=provider,proto3" form:"provider" json:"provider" query:"provider"`
	AppId       string `protobuf:"bytes,4,opt,name=appId,proto3" form:"appId" json:"appId" query:"appId"`
}

func (x *ChatApp) Reset() {
	*x = ChatApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatApp) ProtoMessage() {}

func (x *ChatApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatApp.ProtoReflect.Descriptor instead.
func (*ChatApp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{0}
}

func (x *ChatApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatApp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChatApp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ChatApp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type TTSApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" form:"description" json:"description" query:"description"`
	Provider    string `protobuf:"bytes,3,opt,name=provider,proto3" form:"provider" json:"provider" query:"provider"`
	AppId       string `protobuf:"bytes,4,opt,name=appId,proto3" form:"appId" json:"appId" query:"appId"`
	Speaker     string `protobuf:"bytes,5,opt,name=speaker,proto3" form:"speaker" json:"speaker" query:"speaker"`
}

func (x *TTSApp) Reset() {
	*x = TTSApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTSApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSApp) ProtoMessage() {}

func (x *TTSApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSApp.ProtoReflect.Descriptor instead.
func (*TTSApp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{1}
}

func (x *TTSApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TTSApp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TTSApp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TTSApp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *TTSApp) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

type ReportApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" form:"description" json:"description" query:"description"`
	Provider    string `protobuf:"bytes,3,opt,name=provider,proto3" form:"provider" json:"provider" query:"provider"`
	AppId       string `protobuf:"bytes,4,opt,name=appId,proto3" form:"appId" json:"appId" query:"appId"`
}

func (x *ReportApp) Reset() {
	*x = ReportApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportApp) ProtoMessage() {}

func (x *ReportApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportApp.ProtoReflect.Descriptor instead.
func (*ReportApp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{2}
}

func (x *ReportApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportApp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReportApp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReportApp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ConfigVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId     string     `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
	Type       int32      `protobuf:"varint,2,opt,name=type,proto3" form:"type" json:"type" query:"type"` // chain | end2end
	Chat       *ChatApp   `protobuf:"bytes,3,opt,name=chat,proto3" form:"chat" json:"chat" query:"chat"`
	Tts        *TTSApp    `protobuf:"bytes,4,opt,name=tts,proto3" form:"tts" json:"tts" query:"tts"`
	Report     *ReportApp `protobuf:"bytes,5,opt,name=report,proto3" form:"report" json:"report" query:"report"`
	Status     int32      `protobuf:"varint,6,opt,name=status,proto3" form:"status" json:"status" query:"status"` // active | deleted
	CreateTime int64      `protobuf:"varint,7,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
	UpdateTime int64      `protobuf:"varint,8,opt,name=updateTime,proto3" form:"updateTime" json:"updateTime" query:"updateTime"`
}

func (x *ConfigVO) Reset() {
	*x = ConfigVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVO) ProtoMessage() {}

func (x *ConfigVO) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVO.ProtoReflect.Descriptor instead.
func (*ConfigVO) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigVO) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ConfigVO) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ConfigVO) GetChat() *ChatApp {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *ConfigVO) GetTts() *TTSApp {
	if x != nil {
		return x.Tts
	}
	return nil
}

func (x *ConfigVO) GetReport() *ReportApp {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ConfigVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ConfigVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ConfigVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type ConfigCreateOrUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *ConfigVO `protobuf:"bytes,1,opt,name=config,proto3" form:"config" json:"config" query:"config"`
	Admin  bool      `protobuf:"varint,2,opt,name=admin,proto3" form:"admin" json:"admin" query:"admin"`
}

func (x *ConfigCreateOrUpdateReq) Reset() {
	*x = ConfigCreateOrUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigCreateOrUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigCreateOrUpdateReq) ProtoMessage() {}

func (x *ConfigCreateOrUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigCreateOrUpdateReq.ProtoReflect.Descriptor instead.
func (*ConfigCreateOrUpdateReq) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigCreateOrUpdateReq) GetConfig() *ConfigVO {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigCreateOrUpdateReq) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type ConfigGetByUnitIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId string `protobuf:"bytes,1,opt,name=unitId,proto3" json:"unitId" query:"unitId"`
	Admin  bool   `protobuf:"varint,2,opt,name=admin,proto3" json:"admin" query:"admin"`
}

func (x *ConfigGetByUnitIdReq) Reset() {
	*x = ConfigGetByUnitIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetByUnitIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetByUnitIdReq) ProtoMessage() {}

func (x *ConfigGetByUnitIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetByUnitIdReq.ProtoReflect.Descriptor instead.
func (*ConfigGetByUnitIdReq) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigGetByUnitIdReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ConfigGetByUnitIdReq) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type ConfigGetByUnitIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *ConfigVO `protobuf:"bytes,1,opt,name=config,proto3" form:"config" json:"config" query:"config"`
	Code   int32     `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg    string    `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *ConfigGetByUnitIdResp) Reset() {
	*x = ConfigGetByUnitIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetByUnitIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetByUnitIdResp) ProtoMessage() {}

func (x *ConfigGetByUnitIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetByUnitIdResp.ProtoReflect.Descriptor instead.
func (*ConfigGetByUnitIdResp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigGetByUnitIdResp) GetConfig() *ConfigVO {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigGetByUnitIdResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigGetByUnitIdResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_core_api_config_proto protoreflect.FileDescriptor

var file_core_api_config_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x1a, 0x16, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x06, 0x54, 0x54, 0x53, 0x41,
	0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70,
	0x65, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x65,
	0x61, 0x6b, 0x65, 0x72, 0x22, 0x73, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x70,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x86, 0x02, 0x0a, 0x08, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x56, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x41, 0x70, 0x70, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x12, 0x22, 0x0a, 0x03, 0x74, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x54, 0x53, 0x41, 0x70, 0x70, 0x52, 0x03, 0x74, 0x74, 0x73, 0x12, 0x2b, 0x0a,
	0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41,
	0x70, 0x70, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56,
	0x4f, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22,
	0x5b, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x6e,
	0x69, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xb2, 0xbb, 0x18, 0x06, 0x75, 0x6e, 0x69,
	0x74, 0x49, 0x64, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x05, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x42, 0x09, 0xb2, 0xbb, 0x18, 0x05,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x6b, 0x0a, 0x15,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x4f, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70, 0x6f, 0x6c, 0x61, 0x72,
	0x69, 0x73, 0x2f, 0x70, 0x73, 0x79, 0x63, 0x68, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_api_config_proto_rawDescOnce sync.Once
	file_core_api_config_proto_rawDescData = file_core_api_config_proto_rawDesc
)

func file_core_api_config_proto_rawDescGZIP() []byte {
	file_core_api_config_proto_rawDescOnce.Do(func() {
		file_core_api_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_config_proto_rawDescData)
	})
	return file_core_api_config_proto_rawDescData
}

var file_core_api_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_api_config_proto_goTypes = []interface{}{
	(*ChatApp)(nil),                 // 0: core_api.ChatApp
	(*TTSApp)(nil),                  // 1: core_api.TTSApp
	(*ReportApp)(nil),               // 2: core_api.ReportApp
	(*ConfigVO)(nil),                // 3: core_api.ConfigVO
	(*ConfigCreateOrUpdateReq)(nil), // 4: core_api.ConfigCreateOrUpdateReq
	(*ConfigGetByUnitIdReq)(nil),    // 5: core_api.ConfigGetByUnitIdReq
	(*ConfigGetByUnitIdResp)(nil),   // 6: core_api.ConfigGetByUnitIdResp
}
var file_core_api_config_proto_depIdxs = []int32{
	0, // 0: core_api.ConfigVO.chat:type_name -> core_api.ChatApp
	1, // 1: core_api.ConfigVO.tts:type_name -> core_api.TTSApp
	2, // 2: core_api.ConfigVO.report:type_name -> core_api.ReportApp
	3, // 3: core_api.ConfigCreateOrUpdateReq.config:type_name -> core_api.ConfigVO
	3, // 4: core_api.ConfigGetByUnitIdResp.config:type_name -> core_api.ConfigVO
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func file_core_api_config_proto_init() {
	if File_core_api_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_api_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTSApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigCreateOrUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigGetByUnitIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigGetByUnitIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_api_config_proto_goTypes,
		DependencyIndexes: file_core_api_config_proto_depIdxs,
		MessageInfos:      file_core_api_config_proto_msgTypes,
	}.Build()
	File_core_api_config_proto = out.File
	file_core_api_config_proto_rawDesc = nil
	file_core_api_config_proto_goTypes = nil
	file_core_api_config_proto_depIdxs = nil
}
