// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: core_api/config.proto

package core_api

import (
	_ "github.com/xh-polaris/psych-core-api/biz/application/dto/basic"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 聊天应用配置
type ChatApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" form:"description" json:"description" query:"description"`
	Provider    string `protobuf:"bytes,3,opt,name=provider,proto3" form:"provider" json:"provider" query:"provider"`
	AppId       string `protobuf:"bytes,4,opt,name=appId,proto3" form:"appId" json:"appId" query:"appId"`
}

func (x *ChatApp) Reset() {
	*x = ChatApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatApp) ProtoMessage() {}

func (x *ChatApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatApp.ProtoReflect.Descriptor instead.
func (*ChatApp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{0}
}

func (x *ChatApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatApp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChatApp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ChatApp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// TTS应用配置
type TTSApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" form:"description" json:"description" query:"description"`
	Provider    string `protobuf:"bytes,3,opt,name=provider,proto3" form:"provider" json:"provider" query:"provider"`
	AppId       string `protobuf:"bytes,4,opt,name=appId,proto3" form:"appId" json:"appId" query:"appId"`
	Speaker     string `protobuf:"bytes,5,opt,name=speaker,proto3" form:"speaker" json:"speaker" query:"speaker"`
}

func (x *TTSApp) Reset() {
	*x = TTSApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TTSApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSApp) ProtoMessage() {}

func (x *TTSApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSApp.ProtoReflect.Descriptor instead.
func (*TTSApp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{1}
}

func (x *TTSApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TTSApp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TTSApp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TTSApp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *TTSApp) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

// 报表应用配置
type ReportApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" form:"description" json:"description" query:"description"`
	Provider    string `protobuf:"bytes,3,opt,name=provider,proto3" form:"provider" json:"provider" query:"provider"`
	AppId       string `protobuf:"bytes,4,opt,name=appId,proto3" form:"appId" json:"appId" query:"appId"`
}

func (x *ReportApp) Reset() {
	*x = ReportApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportApp) ProtoMessage() {}

func (x *ReportApp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportApp.ProtoReflect.Descriptor instead.
func (*ReportApp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{2}
}

func (x *ReportApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportApp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReportApp) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReportApp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

// 心理老师虚拟形象
type Character struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 角色ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" form:"id" json:"id" query:"id"`
	// 教师名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	// 音色配置
	Voice string `protobuf:"bytes,3,opt,name=voice,proto3" form:"voice" json:"voice" query:"voice"`
	// 形象图片url
	Image string `protobuf:"bytes,4,opt,name=image,proto3" form:"image" json:"image" query:"image"`
	// 是否删除
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" form:"status" json:"status" query:"status"`
}

func (x *Character) Reset() {
	*x = Character{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{3}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *Character) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Character) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 单位配置
type ConfigVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId string `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
	// 1-2: Chain | End2End
	Type   int32      `protobuf:"varint,2,opt,name=type,proto3" form:"type" json:"type" query:"type"`
	Chat   *ChatApp   `protobuf:"bytes,3,opt,name=chat,proto3" form:"chat" json:"chat" query:"chat"`
	Tts    *TTSApp    `protobuf:"bytes,4,opt,name=tts,proto3" form:"tts" json:"tts" query:"tts"`
	Report *ReportApp `protobuf:"bytes,5,opt,name=report,proto3" form:"report" json:"report" query:"report"`
	// 1-2: Active | Deleted
	Status          int32  `protobuf:"varint,6,opt,name=status,proto3" form:"status" json:"status" query:"status"`
	CreateTime      int64  `protobuf:"varint,7,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
	UpdateTime      int64  `protobuf:"varint,8,opt,name=updateTime,proto3" form:"updateTime" json:"updateTime" query:"updateTime"`
	ModelView       string `protobuf:"bytes,9,opt,name=modelView,proto3" form:"modelView" json:"modelView" query:"modelView"`
	BackgroundImage string `protobuf:"bytes,10,opt,name=backgroundImage,proto3" form:"backgroundImage" json:"backgroundImage" query:"backgroundImage"`
	// 心理老师形象列表
	Characters []*Character `protobuf:"bytes,11,rep,name=characters,proto3" form:"characters" json:"characters" query:"characters"`
	// 对话背景图列表
	Scene []string `protobuf:"bytes,12,rep,name=scene,proto3" form:"scene" json:"scene" query:"scene"`
	// 接收告警的手机号
	AlertPhone []string `protobuf:"bytes,13,rep,name=alertPhone,proto3" form:"alertPhone" json:"alertPhone" query:"alertPhone"`
}

func (x *ConfigVO) Reset() {
	*x = ConfigVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVO) ProtoMessage() {}

func (x *ConfigVO) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVO.ProtoReflect.Descriptor instead.
func (*ConfigVO) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigVO) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *ConfigVO) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ConfigVO) GetChat() *ChatApp {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *ConfigVO) GetTts() *TTSApp {
	if x != nil {
		return x.Tts
	}
	return nil
}

func (x *ConfigVO) GetReport() *ReportApp {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *ConfigVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ConfigVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ConfigVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *ConfigVO) GetModelView() string {
	if x != nil {
		return x.ModelView
	}
	return ""
}

func (x *ConfigVO) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *ConfigVO) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *ConfigVO) GetScene() []string {
	if x != nil {
		return x.Scene
	}
	return nil
}

func (x *ConfigVO) GetAlertPhone() []string {
	if x != nil {
		return x.AlertPhone
	}
	return nil
}

// 创建或更新配置请求
type ConfigCreateOrUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *ConfigVO `protobuf:"bytes,1,opt,name=config,proto3" form:"config" json:"config" query:"config"`
}

func (x *ConfigCreateOrUpdateReq) Reset() {
	*x = ConfigCreateOrUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigCreateOrUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigCreateOrUpdateReq) ProtoMessage() {}

func (x *ConfigCreateOrUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigCreateOrUpdateReq.ProtoReflect.Descriptor instead.
func (*ConfigCreateOrUpdateReq) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigCreateOrUpdateReq) GetConfig() *ConfigVO {
	if x != nil {
		return x.Config
	}
	return nil
}

// 根据单位ID获取配置请求
type ConfigGetByUnitIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId string `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
}

func (x *ConfigGetByUnitIdReq) Reset() {
	*x = ConfigGetByUnitIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetByUnitIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetByUnitIdReq) ProtoMessage() {}

func (x *ConfigGetByUnitIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetByUnitIdReq.ProtoReflect.Descriptor instead.
func (*ConfigGetByUnitIdReq) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigGetByUnitIdReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

// 根据单位ID获取配置响应
type ConfigGetByUnitIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *ConfigVO `protobuf:"bytes,1,opt,name=config,proto3" form:"config" json:"config" query:"config"`
	Code   int32     `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg    string    `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *ConfigGetByUnitIdResp) Reset() {
	*x = ConfigGetByUnitIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetByUnitIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetByUnitIdResp) ProtoMessage() {}

func (x *ConfigGetByUnitIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetByUnitIdResp.ProtoReflect.Descriptor instead.
func (*ConfigGetByUnitIdResp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigGetByUnitIdResp) GetConfig() *ConfigVO {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigGetByUnitIdResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigGetByUnitIdResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取展示信息请求（无需鉴权）
type ConfigGetCharacterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId string `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
}

func (x *ConfigGetCharacterReq) Reset() {
	*x = ConfigGetCharacterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetCharacterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetCharacterReq) ProtoMessage() {}

func (x *ConfigGetCharacterReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetCharacterReq.ProtoReflect.Descriptor instead.
func (*ConfigGetCharacterReq) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigGetCharacterReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

// 获取展示信息响应（只返回展示相关字段）
type ConfigGetCharacterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 心理老师形象列表
	Characters []*Character `protobuf:"bytes,1,rep,name=characters,proto3" form:"characters" json:"characters" query:"characters"`
	// 对话背景图列表
	Scene []string `protobuf:"bytes,2,rep,name=scene,proto3" form:"scene" json:"scene" query:"scene"`
	Code  int32    `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg   string   `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *ConfigGetCharacterResp) Reset() {
	*x = ConfigGetCharacterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_config_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetCharacterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetCharacterResp) ProtoMessage() {}

func (x *ConfigGetCharacterResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_config_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetCharacterResp.ProtoReflect.Descriptor instead.
func (*ConfigGetCharacterResp) Descriptor() ([]byte, []int) {
	return file_core_api_config_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigGetCharacterResp) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *ConfigGetCharacterResp) GetScene() []string {
	if x != nil {
		return x.Scene
	}
	return nil
}

func (x *ConfigGetCharacterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigGetCharacterResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_core_api_config_proto protoreflect.FileDescriptor

var file_core_api_config_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x1a, 0x16, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x06, 0x54, 0x54, 0x53, 0x41,
	0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70,
	0x65, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x65,
	0x61, 0x6b, 0x65, 0x72, 0x22, 0x73, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x70,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x09, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xb9,
	0x03, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x41, 0x70, 0x70, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x12, 0x22,
	0x0a, 0x03, 0x74, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x54, 0x53, 0x41, 0x70, 0x70, 0x52, 0x03, 0x74,
	0x74, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x41, 0x70, 0x70, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x56, 0x69, 0x65, 0x77, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x56, 0x69, 0x65, 0x77, 0x12, 0x28, 0x0a, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x33, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x0c, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x45, 0x0a, 0x17, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x4f, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x22, 0x2e, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x55, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49,
	0x64, 0x22, 0x6b, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x55, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56, 0x4f, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2f,
	0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x22,
	0x8b, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x43, 0x5a,
	0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70,
	0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2f, 0x70, 0x73, 0x79, 0x63, 0x68, 0x2d, 0x63, 0x6f, 0x72,
	0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_api_config_proto_rawDescOnce sync.Once
	file_core_api_config_proto_rawDescData = file_core_api_config_proto_rawDesc
)

func file_core_api_config_proto_rawDescGZIP() []byte {
	file_core_api_config_proto_rawDescOnce.Do(func() {
		file_core_api_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_config_proto_rawDescData)
	})
	return file_core_api_config_proto_rawDescData
}

var file_core_api_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_core_api_config_proto_goTypes = []interface{}{
	(*ChatApp)(nil),                 // 0: core_api.ChatApp
	(*TTSApp)(nil),                  // 1: core_api.TTSApp
	(*ReportApp)(nil),               // 2: core_api.ReportApp
	(*Character)(nil),               // 3: core_api.Character
	(*ConfigVO)(nil),                // 4: core_api.ConfigVO
	(*ConfigCreateOrUpdateReq)(nil), // 5: core_api.ConfigCreateOrUpdateReq
	(*ConfigGetByUnitIdReq)(nil),    // 6: core_api.ConfigGetByUnitIdReq
	(*ConfigGetByUnitIdResp)(nil),   // 7: core_api.ConfigGetByUnitIdResp
	(*ConfigGetCharacterReq)(nil),   // 8: core_api.ConfigGetCharacterReq
	(*ConfigGetCharacterResp)(nil),  // 9: core_api.ConfigGetCharacterResp
}
var file_core_api_config_proto_depIdxs = []int32{
	0, // 0: core_api.ConfigVO.chat:type_name -> core_api.ChatApp
	1, // 1: core_api.ConfigVO.tts:type_name -> core_api.TTSApp
	2, // 2: core_api.ConfigVO.report:type_name -> core_api.ReportApp
	3, // 3: core_api.ConfigVO.characters:type_name -> core_api.Character
	4, // 4: core_api.ConfigCreateOrUpdateReq.config:type_name -> core_api.ConfigVO
	4, // 5: core_api.ConfigGetByUnitIdResp.config:type_name -> core_api.ConfigVO
	3, // 6: core_api.ConfigGetCharacterResp.characters:type_name -> core_api.Character
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func file_core_api_config_proto_init() {
	if File_core_api_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_api_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TTSApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Character); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigCreateOrUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigGetByUnitIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigGetByUnitIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigGetCharacterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_config_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigGetCharacterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_api_config_proto_goTypes,
		DependencyIndexes: file_core_api_config_proto_depIdxs,
		MessageInfos:      file_core_api_config_proto_msgTypes,
	}.Build()
	File_core_api_config_proto = out.File
	file_core_api_config_proto_rawDesc = nil
	file_core_api_config_proto_goTypes = nil
	file_core_api_config_proto_depIdxs = nil
}
