// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: core_api/conversation.proto

package core_api

import (
	basic "github.com/xh-polaris/psych-core-api/biz/application/dto/basic"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新建对话
type CreateConversationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 目标 AI 心理老师角色；必填，缺失返回参数错误
	CharacterId string `protobuf:"bytes,1,opt,name=characterId,proto3" form:"characterId" json:"characterId" query:"characterId"`
}

func (x *CreateConversationReq) Reset() {
	*x = CreateConversationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationReq) ProtoMessage() {}

func (x *CreateConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationReq.ProtoReflect.Descriptor instead.
func (*CreateConversationReq) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConversationReq) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

type CreateConversationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`
	Code           int32  `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg            string `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *CreateConversationResp) Reset() {
	*x = CreateConversationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResp) ProtoMessage() {}

func (x *CreateConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResp.ProtoReflect.Descriptor instead.
func (*CreateConversationResp) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConversationResp) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CreateConversationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateConversationResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 对话列表
type ListConversationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaginationOptions *basic.PaginationOptions `protobuf:"bytes,1,opt,name=paginationOptions,proto3" form:"paginationOptions" json:"paginationOptions" query:"paginationOptions"`
	StartDate         string                   `protobuf:"bytes,2,opt,name=startDate,proto3" form:"startDate" json:"startDate" query:"startDate"`
	EndDate           string                   `protobuf:"bytes,3,opt,name=endDate,proto3" form:"endDate" json:"endDate" query:"endDate"`
}

func (x *ListConversationsReq) Reset() {
	*x = ListConversationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsReq) ProtoMessage() {}

func (x *ListConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsReq.ProtoReflect.Descriptor instead.
func (*ListConversationsReq) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *ListConversationsReq) GetPaginationOptions() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOptions
	}
	return nil
}

func (x *ListConversationsReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListConversationsReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ListConversationsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationList []*ConversationVO `protobuf:"bytes,1,rep,name=conversationList,proto3" form:"conversationList" json:"conversationList" query:"conversationList"`
	Pagination       *basic.Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" form:"pagination" json:"pagination" query:"pagination"`
	Code             int32             `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg              string            `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *ListConversationsResp) Reset() {
	*x = ListConversationsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResp) ProtoMessage() {}

func (x *ListConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResp.ProtoReflect.Descriptor instead.
func (*ListConversationsResp) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *ListConversationsResp) GetConversationList() []*ConversationVO {
	if x != nil {
		return x.ConversationList
	}
	return nil
}

func (x *ListConversationsResp) GetPagination() *basic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListConversationsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListConversationsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获得单次对话下的历史消息
type GetSingleConvReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaginationOptions *basic.PaginationOptions `protobuf:"bytes,1,opt,name=paginationOptions,proto3" form:"paginationOptions" json:"paginationOptions" query:"paginationOptions"`
	ConversationId    string                   `protobuf:"bytes,2,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`
}

func (x *GetSingleConvReq) Reset() {
	*x = GetSingleConvReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleConvReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleConvReq) ProtoMessage() {}

func (x *GetSingleConvReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleConvReq.ProtoReflect.Descriptor instead.
func (*GetSingleConvReq) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *GetSingleConvReq) GetPaginationOptions() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOptions
	}
	return nil
}

func (x *GetSingleConvReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetSingleConvResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination  *basic.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" form:"pagination" json:"pagination" query:"pagination"`
	MessageList []*Message        `protobuf:"bytes,2,rep,name=messageList,proto3" form:"messageList" json:"messageList" query:"messageList"`
	Code        int32             `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg         string            `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *GetSingleConvResp) Reset() {
	*x = GetSingleConvResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleConvResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleConvResp) ProtoMessage() {}

func (x *GetSingleConvResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleConvResp.ProtoReflect.Descriptor instead.
func (*GetSingleConvResp) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *GetSingleConvResp) GetPagination() *basic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetSingleConvResp) GetMessageList() []*Message {
	if x != nil {
		return x.MessageList
	}
	return nil
}

func (x *GetSingleConvResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSingleConvResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ConversationVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`
	// 对话标题
	Brief      string `protobuf:"bytes,2,opt,name=brief,proto3" form:"brief" json:"brief" query:"brief"`
	CreateTime int64  `protobuf:"varint,3,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
	UpdateTime int64  `protobuf:"varint,4,opt,name=updateTime,proto3" form:"updateTime" json:"updateTime" query:"updateTime"`
	Date       string `protobuf:"bytes,5,opt,name=date,proto3" form:"date" json:"date" query:"date"`
	// 对话角色ID，绑定单次对话与character
	CharacterId string `protobuf:"bytes,6,opt,name=characterId,proto3" form:"characterId" json:"characterId" query:"characterId"`
}

func (x *ConversationVO) Reset() {
	*x = ConversationVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConversationVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationVO) ProtoMessage() {}

func (x *ConversationVO) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationVO.ProtoReflect.Descriptor instead.
func (*ConversationVO) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationVO) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationVO) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *ConversationVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ConversationVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *ConversationVO) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ConversationVO) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" form:"content" json:"content" query:"content"`
	// 角色, system/assistant/user/tool, 依次为1,2,3,4
	Role int32 `protobuf:"varint,2,opt,name=role,proto3" form:"role" json:"role" query:"role"`
	// 消息索引
	Index int32 `protobuf:"varint,3,opt,name=index,proto3" form:"index" json:"index" query:"index"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *Message) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 按天获取指定老师当天会话的历史消息（学生端恢复某位老师当天聊天）
type GetConvByDateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaginationOptions *basic.PaginationOptions `protobuf:"bytes,1,opt,name=paginationOptions,proto3" form:"paginationOptions" json:"paginationOptions" query:"paginationOptions"`
	Date              string                   `protobuf:"bytes,2,opt,name=date,proto3" form:"date" json:"date" query:"date"`
	UserId            string                   `protobuf:"bytes,3,opt,name=userId,proto3" form:"userId" json:"userId" query:"userId"`
	// 目标 AI 心理老师角色；必填。精确读取单个会话请使用 GetSingleConv
	CharacterId string `protobuf:"bytes,4,opt,name=characterId,proto3" form:"characterId" json:"characterId" query:"characterId"`
}

func (x *GetConvByDateReq) Reset() {
	*x = GetConvByDateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConvByDateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvByDateReq) ProtoMessage() {}

func (x *GetConvByDateReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvByDateReq.ProtoReflect.Descriptor instead.
func (*GetConvByDateReq) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *GetConvByDateReq) GetPaginationOptions() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOptions
	}
	return nil
}

func (x *GetConvByDateReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetConvByDateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetConvByDateReq) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

type GetConvByDateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination  *basic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" form:"pagination" json:"pagination" query:"pagination"`
	MessageList []*ConvByDateMessage `protobuf:"bytes,2,rep,name=messageList,proto3" form:"messageList" json:"messageList" query:"messageList"`
	Code        int32                `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg         string               `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *GetConvByDateResp) Reset() {
	*x = GetConvByDateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConvByDateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvByDateResp) ProtoMessage() {}

func (x *GetConvByDateResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvByDateResp.ProtoReflect.Descriptor instead.
func (*GetConvByDateResp) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *GetConvByDateResp) GetPagination() *basic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetConvByDateResp) GetMessageList() []*ConvByDateMessage {
	if x != nil {
		return x.MessageList
	}
	return nil
}

func (x *GetConvByDateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetConvByDateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ConvByDateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`
	Content        string `protobuf:"bytes,2,opt,name=content,proto3" form:"content" json:"content" query:"content"`
	Role           int32  `protobuf:"varint,3,opt,name=role,proto3" form:"role" json:"role" query:"role"`
	Index          int32  `protobuf:"varint,4,opt,name=index,proto3" form:"index" json:"index" query:"index"`
	CreateTime     int64  `protobuf:"varint,5,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
}

func (x *ConvByDateMessage) Reset() {
	*x = ConvByDateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvByDateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvByDateMessage) ProtoMessage() {}

func (x *ConvByDateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvByDateMessage.ProtoReflect.Descriptor instead.
func (*ConvByDateMessage) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *ConvByDateMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConvByDateMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConvByDateMessage) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *ConvByDateMessage) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ConvByDateMessage) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// SSEEvent
type SSEEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 事件数据
	EventData string `protobuf:"bytes,1,opt,name=eventData,proto3" form:"eventData" json:"eventData" query:"eventData"`
	// 事件id
	EventId int32 `protobuf:"varint,2,opt,name=eventId,proto3" form:"eventId" json:"eventId" query:"eventId"`
	// 事件类型
	EventType int32 `protobuf:"varint,3,opt,name=eventType,proto3" form:"eventType" json:"eventType" query:"eventType"`
}

func (x *SSEEvent) Reset() {
	*x = SSEEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_conversation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSEEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSEEvent) ProtoMessage() {}

func (x *SSEEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_conversation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSEEvent.ProtoReflect.Descriptor instead.
func (*SSEEvent) Descriptor() ([]byte, []int) {
	return file_core_api_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *SSEEvent) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

func (x *SSEEvent) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *SSEEvent) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

var File_core_api_conversation_proto protoreflect.FileDescriptor

var file_core_api_conversation_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63,
	0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x16, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x39, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x96, 0x01, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x46, 0x0a,
	0x11, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x11, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0xb8, 0x01,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x4f, 0x52, 0x10, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x82, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x12, 0x46, 0x0a,
	0x11, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x11, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xa3, 0x01,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0xc4, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x4f, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x72, 0x69, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x72, 0x69, 0x65, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0xa8, 0x01, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x76, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x46,
	0x0a, 0x11, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x11, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x22, 0xad, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x76,
	0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6e, 0x76, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x9f, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x76, 0x42, 0x79, 0x44,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x08, 0x53, 0x53, 0x45, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69,
	0x73, 0x2f, 0x70, 0x73, 0x79, 0x63, 0x68, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_api_conversation_proto_rawDescOnce sync.Once
	file_core_api_conversation_proto_rawDescData = file_core_api_conversation_proto_rawDesc
)

func file_core_api_conversation_proto_rawDescGZIP() []byte {
	file_core_api_conversation_proto_rawDescOnce.Do(func() {
		file_core_api_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_conversation_proto_rawDescData)
	})
	return file_core_api_conversation_proto_rawDescData
}

var file_core_api_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_core_api_conversation_proto_goTypes = []interface{}{
	(*CreateConversationReq)(nil),   // 0: core_api.CreateConversationReq
	(*CreateConversationResp)(nil),  // 1: core_api.CreateConversationResp
	(*ListConversationsReq)(nil),    // 2: core_api.ListConversationsReq
	(*ListConversationsResp)(nil),   // 3: core_api.ListConversationsResp
	(*GetSingleConvReq)(nil),        // 4: core_api.GetSingleConvReq
	(*GetSingleConvResp)(nil),       // 5: core_api.GetSingleConvResp
	(*ConversationVO)(nil),          // 6: core_api.ConversationVO
	(*Message)(nil),                 // 7: core_api.Message
	(*GetConvByDateReq)(nil),        // 8: core_api.GetConvByDateReq
	(*GetConvByDateResp)(nil),       // 9: core_api.GetConvByDateResp
	(*ConvByDateMessage)(nil),       // 10: core_api.ConvByDateMessage
	(*SSEEvent)(nil),                // 11: core_api.SSEEvent
	(*basic.PaginationOptions)(nil), // 12: basic.PaginationOptions
	(*basic.Pagination)(nil),        // 13: basic.Pagination
}
var file_core_api_conversation_proto_depIdxs = []int32{
	12, // 0: core_api.ListConversationsReq.paginationOptions:type_name -> basic.PaginationOptions
	6,  // 1: core_api.ListConversationsResp.conversationList:type_name -> core_api.ConversationVO
	13, // 2: core_api.ListConversationsResp.pagination:type_name -> basic.Pagination
	12, // 3: core_api.GetSingleConvReq.paginationOptions:type_name -> basic.PaginationOptions
	13, // 4: core_api.GetSingleConvResp.pagination:type_name -> basic.Pagination
	7,  // 5: core_api.GetSingleConvResp.messageList:type_name -> core_api.Message
	12, // 6: core_api.GetConvByDateReq.paginationOptions:type_name -> basic.PaginationOptions
	13, // 7: core_api.GetConvByDateResp.pagination:type_name -> basic.Pagination
	10, // 8: core_api.GetConvByDateResp.messageList:type_name -> core_api.ConvByDateMessage
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}


func file_core_api_conversation_proto_init() {
	if File_core_api_conversation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_api_conversation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConversationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConversationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConversationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConversationsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleConvReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleConvResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConversationVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConvByDateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConvByDateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvByDateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_conversation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSEEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_conversation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_api_conversation_proto_goTypes,
		DependencyIndexes: file_core_api_conversation_proto_depIdxs,
		MessageInfos:      file_core_api_conversation_proto_msgTypes,
	}.Build()
	File_core_api_conversation_proto = out.File
	file_core_api_conversation_proto_rawDesc = nil
	file_core_api_conversation_proto_goTypes = nil
	file_core_api_conversation_proto_depIdxs = nil
}
