// Code generated by protoc-gen-go. DO NOT EDIT. (manual additions for typed analysis/report)
package core_api

// ========== Analysis (13 dimensions) ==========

type ProblemItem struct {
	Category    string `protobuf:"bytes,1,opt,name=category,proto3" json:"category"`
	Subcategory string `protobuf:"bytes,2,opt,name=subcategory,proto3" json:"subcategory"`
}

type AnalysisProblem struct {
	Primary   *ProblemItem   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary"`
	Secondary []*ProblemItem `protobuf:"bytes,2,rep,name=secondary,proto3" json:"secondary,omitempty"`
}

type AnalysisEmotion struct {
	Type      []string `protobuf:"bytes,1,rep,name=type,proto3" json:"type"`
	Intensity string   `protobuf:"bytes,2,opt,name=intensity,proto3" json:"intensity"`
}

type AnalysisSupport struct {
	Family              bool     `protobuf:"varint,1,opt,name=family,proto3" json:"family"`
	Teacher             bool     `protobuf:"varint,2,opt,name=teacher,proto3" json:"teacher"`
	Friend              bool     `protobuf:"varint,3,opt,name=friend,proto3" json:"friend"`
	Other               []string `protobuf:"bytes,4,rep,name=other,proto3" json:"other,omitempty"`
	ProtectiveResources []string `protobuf:"bytes,5,rep,name=protectiveResources,proto3" json:"protectiveResources,omitempty"`
}

type AnalysisFunction struct {
	Learning      string `protobuf:"bytes,1,opt,name=learning,proto3" json:"learning"`
	Sleep         string `protobuf:"bytes,2,opt,name=sleep,proto3" json:"sleep"`
	Diet          string `protobuf:"bytes,3,opt,name=diet,proto3" json:"diet"`
	Interpersonal string `protobuf:"bytes,4,opt,name=interpersonal,proto3" json:"interpersonal"`
	DailyLife     string `protobuf:"bytes,5,opt,name=dailyLife,proto3" json:"dailyLife"`
}

type AnalysisDistress struct {
	Level  string   `protobuf:"bytes,1,opt,name=level,proto3" json:"level"`
	Reason []string `protobuf:"bytes,2,rep,name=reason,proto3" json:"reason,omitempty"`
}

type RiskScore struct {
	CurrentIdeation     int32 `protobuf:"varint,1,opt,name=currentIdeation,proto3" json:"currentIdeation"`
	History             int32 `protobuf:"varint,2,opt,name=history,proto3" json:"history"`
	CurrentStress       int32 `protobuf:"varint,3,opt,name=currentStress,proto3" json:"currentStress"`
	ProtectiveResources int32 `protobuf:"varint,4,opt,name=protectiveResources,proto3" json:"protectiveResources"`
	MentalHealthHistory int32 `protobuf:"varint,5,opt,name=mentalHealthHistory,proto3" json:"mentalHealthHistory"`
	Total               int32 `protobuf:"varint,6,opt,name=total,proto3" json:"total"`
}

type ProfileSection struct {
	Summary string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary"`
	Items   []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

type RiskProfile struct {
	CurrentRisk       *ProfileSection            `protobuf:"bytes,1,opt,name=currentRisk,proto3" json:"currentRisk"`
	Stressors         *ProfileSection            `protobuf:"bytes,2,opt,name=stressors,proto3" json:"stressors"`
	RiskFactors       *ProfileSection            `protobuf:"bytes,3,opt,name=riskFactors,proto3" json:"riskFactors"`
	ProtectiveFactors *ProfileSection            `protobuf:"bytes,4,opt,name=protectiveFactors,proto3" json:"protectiveFactors"`
	InformationGap    *ProfileSection            `protobuf:"bytes,5,opt,name=informationGap,proto3" json:"informationGap"`
	CurrentSafety     *RiskProfile_CurrentSafety `protobuf:"bytes,6,opt,name=currentSafety,proto3" json:"currentSafety"`
}

type RiskProfile_CurrentSafety struct {
	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status"`
}

type AnalysisRisk struct {
	Level    string       `protobuf:"bytes,1,opt,name=level,proto3" json:"level"`
	Score    *RiskScore   `protobuf:"bytes,2,opt,name=score,proto3" json:"score"`
	Profile  *RiskProfile `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile"`
	Evidence []string     `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Action   string       `protobuf:"bytes,5,opt,name=action,proto3" json:"action"`
}

type AnalysisConfidence struct {
	Overall string `protobuf:"bytes,1,opt,name=overall,proto3" json:"overall"`
	Risk    string `protobuf:"bytes,2,opt,name=risk,proto3" json:"risk"`
	Reason  string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason"`
}

type ReportAnalysis struct {
	Problem     *AnalysisProblem    `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem"`
	Emotion     *AnalysisEmotion    `protobuf:"bytes,2,opt,name=emotion,proto3" json:"emotion"`
	Cognition   []string            `protobuf:"bytes,3,rep,name=cognition,proto3" json:"cognition,omitempty"`
	Behavior    []string            `protobuf:"bytes,4,rep,name=behavior,proto3" json:"behavior,omitempty"`
	Duration    string              `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration"`
	Trigger     []string            `protobuf:"bytes,6,rep,name=trigger,proto3" json:"trigger,omitempty"`
	Coping      []string            `protobuf:"bytes,7,rep,name=coping,proto3" json:"coping,omitempty"`
	Support     *AnalysisSupport    `protobuf:"bytes,8,opt,name=support,proto3" json:"support"`
	HelpSeeking string              `protobuf:"bytes,9,opt,name=helpSeeking,proto3" json:"helpSeeking"`
	Function    *AnalysisFunction   `protobuf:"bytes,10,opt,name=function,proto3" json:"function"`
	Distress    *AnalysisDistress   `protobuf:"bytes,11,opt,name=distress,proto3" json:"distress"`
	Risk        *AnalysisRisk       `protobuf:"bytes,12,opt,name=risk,proto3" json:"risk"`
	Confidence  *AnalysisConfidence `protobuf:"bytes,13,opt,name=confidence,proto3" json:"confidence"`
	MissingInfo []string            `protobuf:"bytes,14,rep,name=missingInfo,proto3" json:"missingInfo,omitempty"`
}

// ========== SimpleReport (16 sections) ==========

type ReportEmotion struct {
	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type"`
	Intensity string `protobuf:"bytes,2,opt,name=intensity,proto3" json:"intensity"`
}

type ReportRiskObs struct {
	Level    string `protobuf:"bytes,1,opt,name=level,proto3" json:"level"`
	Evidence string `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
}

type ReportSeverity struct {
	Level string `protobuf:"bytes,1,opt,name=level,proto3" json:"level"`
	Basis string `protobuf:"bytes,2,opt,name=basis,proto3" json:"basis"`
}

type ReportSummary struct {
	MainProblem  string `protobuf:"bytes,1,opt,name=mainProblem,proto3" json:"mainProblem"`
	EmotionState string `protobuf:"bytes,2,opt,name=emotionState,proto3" json:"emotionState"`
	Severity     string `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity"`
	RiskLevel    string `protobuf:"bytes,4,opt,name=riskLevel,proto3" json:"riskLevel"`
	Focus        string `protobuf:"bytes,5,opt,name=focus,proto3" json:"focus"`
}

type SimpleReportMsg struct {
	MainProblem        string          `protobuf:"bytes,1,opt,name=mainProblem,proto3" json:"mainProblem"`
	Emotion            *ReportEmotion  `protobuf:"bytes,2,opt,name=emotion,proto3" json:"emotion"`
	Thoughts           string          `protobuf:"bytes,3,opt,name=thoughts,proto3" json:"thoughts"`
	Behaviors          []string        `protobuf:"bytes,4,rep,name=behaviors,proto3" json:"behaviors,omitempty"`
	Needs              []string        `protobuf:"bytes,5,rep,name=needs,proto3" json:"needs,omitempty"`
	Duration           string          `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration"`
	FunctionImpact     string          `protobuf:"bytes,7,opt,name=functionImpact,proto3" json:"functionImpact"`
	Triggers           string          `protobuf:"bytes,8,opt,name=triggers,proto3" json:"triggers"`
	Coping             string          `protobuf:"bytes,9,opt,name=coping,proto3" json:"coping"`
	Support            string          `protobuf:"bytes,10,opt,name=support,proto3" json:"support"`
	HelpSeeking        string          `protobuf:"bytes,11,opt,name=helpSeeking,proto3" json:"helpSeeking"`
	RiskObservation    *ReportRiskObs  `protobuf:"bytes,12,opt,name=riskObservation,proto3" json:"riskObservation"`
	SeverityAssessment *ReportSeverity `protobuf:"bytes,13,opt,name=severityAssessment,proto3" json:"severityAssessment"`
	Summary            *ReportSummary  `protobuf:"bytes,14,opt,name=summary,proto3" json:"summary"`
	ProvidedSupport    string          `protobuf:"bytes,15,opt,name=providedSupport,proto3" json:"providedSupport"`
	Suggestions        []string        `protobuf:"bytes,16,rep,name=suggestions,proto3" json:"suggestions"`
}
