// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: core_api/unit.proto

package core_api

import (
	_ "github.com/xh-polaris/psych-core-api/biz/application/dto/basic"
	_ "github.com/xh-polaris/psych-core-api/biz/application/dto/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnitVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" form:"id" json:"id" query:"id"`
	Name    string `protobuf:"bytes,4,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Address string `protobuf:"bytes,5,opt,name=address,proto3" form:"address" json:"address" query:"address"`
	Contact string `protobuf:"bytes,6,opt,name=contact,proto3" form:"contact" json:"contact" query:"contact"`
	Level   int32  `protobuf:"varint,7,opt,name=level,proto3" form:"level" json:"level" query:"level"`
	// 1-2: Active | Deleted
	Status     int32 `protobuf:"varint,8,opt,name=status,proto3" form:"status" json:"status" query:"status"`
	CreateTime int64 `protobuf:"varint,9,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
	UpdateTime int64 `protobuf:"varint,10,opt,name=updateTime,proto3" form:"updateTime" json:"updateTime" query:"updateTime"`
	DeleteTime int64 `protobuf:"varint,11,opt,name=deleteTime,proto3" form:"deleteTime" json:"deleteTime" query:"deleteTime"`
}

func (x *UnitVO) Reset() {
	*x = UnitVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_unit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitVO) ProtoMessage() {}

func (x *UnitVO) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_unit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitVO.ProtoReflect.Descriptor instead.
func (*UnitVO) Descriptor() ([]byte, []int) {
	return file_core_api_unit_proto_rawDescGZIP(), []int{0}
}

func (x *UnitVO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnitVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitVO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UnitVO) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *UnitVO) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UnitVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UnitVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UnitVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *UnitVO) GetDeleteTime() int64 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

// 获取信息
type UnitGetInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId string `protobuf:"bytes,1,opt,name=unitId,proto3" json:"unitId" query:"unitId"`
}

func (x *UnitGetInfoReq) Reset() {
	*x = UnitGetInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_unit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitGetInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitGetInfoReq) ProtoMessage() {}

func (x *UnitGetInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_unit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitGetInfoReq.ProtoReflect.Descriptor instead.
func (*UnitGetInfoReq) Descriptor() ([]byte, []int) {
	return file_core_api_unit_proto_rawDescGZIP(), []int{1}
}

func (x *UnitGetInfoReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type UnitGetInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit *UnitVO `protobuf:"bytes,1,opt,name=unit,proto3" form:"unit" json:"unit" query:"unit"`
	Code int32   `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg  string  `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *UnitGetInfoResp) Reset() {
	*x = UnitGetInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_unit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitGetInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitGetInfoResp) ProtoMessage() {}

func (x *UnitGetInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_unit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitGetInfoResp.ProtoReflect.Descriptor instead.
func (*UnitGetInfoResp) Descriptor() ([]byte, []int) {
	return file_core_api_unit_proto_rawDescGZIP(), []int{2}
}

func (x *UnitGetInfoResp) GetUnit() *UnitVO {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *UnitGetInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnitGetInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 更新信息
type UnitUpdateInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unit *UnitVO `protobuf:"bytes,1,opt,name=unit,proto3" form:"unit" json:"unit" query:"unit"`
}

func (x *UnitUpdateInfoReq) Reset() {
	*x = UnitUpdateInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_unit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitUpdateInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitUpdateInfoReq) ProtoMessage() {}

func (x *UnitUpdateInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_unit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitUpdateInfoReq.ProtoReflect.Descriptor instead.
func (*UnitUpdateInfoReq) Descriptor() ([]byte, []int) {
	return file_core_api_unit_proto_rawDescGZIP(), []int{3}
}

func (x *UnitUpdateInfoReq) GetUnit() *UnitVO {
	if x != nil {
		return x.Unit
	}
	return nil
}

// 关联用户
type UnitLinkUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId string `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" form:"userId" json:"userId" query:"userId"`
}

func (x *UnitLinkUserReq) Reset() {
	*x = UnitLinkUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_unit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitLinkUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitLinkUserReq) ProtoMessage() {}

func (x *UnitLinkUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_unit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitLinkUserReq.ProtoReflect.Descriptor instead.
func (*UnitLinkUserReq) Descriptor() ([]byte, []int) {
	return file_core_api_unit_proto_rawDescGZIP(), []int{4}
}

func (x *UnitLinkUserReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UnitLinkUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 创建并关联用户
type UnitCreateAndLinkUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId   string    `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
	CodeType int32     `protobuf:"varint,2,opt,name=codeType,proto3" form:"codeType" json:"codeType" query:"codeType"`
	Users    []*UserVO `protobuf:"bytes,3,rep,name=users,proto3" form:"users" json:"users" query:"users"`
}

func (x *UnitCreateAndLinkUserReq) Reset() {
	*x = UnitCreateAndLinkUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_unit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitCreateAndLinkUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitCreateAndLinkUserReq) ProtoMessage() {}

func (x *UnitCreateAndLinkUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_unit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitCreateAndLinkUserReq.ProtoReflect.Descriptor instead.
func (*UnitCreateAndLinkUserReq) Descriptor() ([]byte, []int) {
	return file_core_api_unit_proto_rawDescGZIP(), []int{5}
}

func (x *UnitCreateAndLinkUserReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UnitCreateAndLinkUserReq) GetCodeType() int32 {
	if x != nil {
		return x.CodeType
	}
	return 0
}

func (x *UnitCreateAndLinkUserReq) GetUsers() []*UserVO {
	if x != nil {
		return x.Users
	}
	return nil
}

type UnitCreateAndLinkUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllCount     int32  `protobuf:"varint,1,opt,name=allCount,proto3" form:"allCount" json:"allCount" query:"allCount"`
	SuccessCount int32  `protobuf:"varint,2,opt,name=successCount,proto3" form:"successCount" json:"successCount" query:"successCount"`
	SkipCount    int32  `protobuf:"varint,3,opt,name=skipCount,proto3" form:"skipCount" json:"skipCount" query:"skipCount"`
	Code         int32  `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg          string `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *UnitCreateAndLinkUserResp) Reset() {
	*x = UnitCreateAndLinkUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_unit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitCreateAndLinkUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitCreateAndLinkUserResp) ProtoMessage() {}

func (x *UnitCreateAndLinkUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_unit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitCreateAndLinkUserResp.ProtoReflect.Descriptor instead.
func (*UnitCreateAndLinkUserResp) Descriptor() ([]byte, []int) {
	return file_core_api_unit_proto_rawDescGZIP(), []int{6}
}

func (x *UnitCreateAndLinkUserResp) GetAllCount() int32 {
	if x != nil {
		return x.AllCount
	}
	return 0
}

func (x *UnitCreateAndLinkUserResp) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *UnitCreateAndLinkUserResp) GetSkipCount() int32 {
	if x != nil {
		return x.SkipCount
	}
	return 0
}

func (x *UnitCreateAndLinkUserResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnitCreateAndLinkUserResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_core_api_unit_proto protoreflect.FileDescriptor

var file_core_api_unit_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x1a,
	0x16, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xee, 0x01, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x74,
	0x56, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x0e, 0x55, 0x6e, 0x69, 0x74,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x06, 0x75, 0x6e,
	0x69, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xb2, 0xbb, 0x18, 0x06,
	0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x22, 0x5f,
	0x0a, 0x0f, 0x55, 0x6e, 0x69, 0x74, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x56,
	0x4f, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x39, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x6e,
	0x69, 0x74, 0x56, 0x4f, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x41, 0x0a, 0x0f, 0x55, 0x6e,
	0x69, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x76, 0x0a,
	0x18, 0x55, 0x6e, 0x69, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x4c, 0x69,
	0x6e, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x56, 0x4f, 0x52, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x19, 0x55, 0x6e, 0x69, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x70, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70, 0x6f, 0x6c, 0x61, 0x72,
	0x69, 0x73, 0x2f, 0x70, 0x73, 0x79, 0x63, 0x68, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_api_unit_proto_rawDescOnce sync.Once
	file_core_api_unit_proto_rawDescData = file_core_api_unit_proto_rawDesc
)

func file_core_api_unit_proto_rawDescGZIP() []byte {
	file_core_api_unit_proto_rawDescOnce.Do(func() {
		file_core_api_unit_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_unit_proto_rawDescData)
	})
	return file_core_api_unit_proto_rawDescData
}

var file_core_api_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_api_unit_proto_goTypes = []interface{}{
	(*UnitVO)(nil),                    // 0: core_api.UnitVO
	(*UnitGetInfoReq)(nil),            // 1: core_api.UnitGetInfoReq
	(*UnitGetInfoResp)(nil),           // 2: core_api.UnitGetInfoResp
	(*UnitUpdateInfoReq)(nil),         // 3: core_api.UnitUpdateInfoReq
	(*UnitLinkUserReq)(nil),           // 4: core_api.UnitLinkUserReq
	(*UnitCreateAndLinkUserReq)(nil),  // 5: core_api.UnitCreateAndLinkUserReq
	(*UnitCreateAndLinkUserResp)(nil), // 6: core_api.UnitCreateAndLinkUserResp
	(*UserVO)(nil),                    // 7: core_api.UserVO
}
var file_core_api_unit_proto_depIdxs = []int32{
	0, // 0: core_api.UnitGetInfoResp.unit:type_name -> core_api.UnitVO
	0, // 1: core_api.UnitUpdateInfoReq.unit:type_name -> core_api.UnitVO
	7, // 2: core_api.UnitCreateAndLinkUserReq.users:type_name -> core_api.UserVO
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func file_core_api_unit_proto_init() {
	if File_core_api_unit_proto != nil {
		return
	}
	file_core_api_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_core_api_unit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_unit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitGetInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_unit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitGetInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_unit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitUpdateInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_unit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitLinkUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_unit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitCreateAndLinkUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_unit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitCreateAndLinkUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_unit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_api_unit_proto_goTypes,
		DependencyIndexes: file_core_api_unit_proto_depIdxs,
		MessageInfos:      file_core_api_unit_proto_msgTypes,
	}.Build()
	File_core_api_unit_proto = out.File
	file_core_api_unit_proto_rawDesc = nil
	file_core_api_unit_proto_goTypes = nil
	file_core_api_unit_proto_depIdxs = nil
}
