// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: core_api/user.proto

package core_api

import (
	_ "github.com/xh-polaris/psych-core-api/biz/application/dto/basic"
	_ "github.com/xh-polaris/psych-core-api/biz/application/dto/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                `protobuf:"bytes,1,opt,name=id,proto3" form:"id" json:"id" query:"id"`
	CodeType   string                `protobuf:"bytes,2,opt,name=codeType,proto3" form:"codeType" json:"codeType" query:"codeType"`
	Code       string                `protobuf:"bytes,3,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Password   string                `protobuf:"bytes,4,opt,name=password,proto3" form:"password" json:"password" query:"password"`
	UnitId     string                `protobuf:"bytes,5,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
	Name       string                `protobuf:"bytes,6,opt,name=name,proto3" form:"name" json:"name" query:"name"`
	Birth      int64                 `protobuf:"varint,7,opt,name=birth,proto3" form:"birth" json:"birth" query:"birth"`
	Gender     string                `protobuf:"bytes,8,opt,name=gender,proto3" form:"gender" json:"gender" query:"gender"`
	Status     string                `protobuf:"bytes,9,opt,name=status,proto3" form:"status" json:"status" query:"status"`
	EnrollYear int32                 `protobuf:"varint,10,opt,name=enrollYear,proto3" form:"enrollYear" json:"enrollYear" query:"enrollYear"`
	Grade      int32                 `protobuf:"varint,11,opt,name=grade,proto3" form:"grade" json:"grade" query:"grade"`
	Class      int32                 `protobuf:"varint,12,opt,name=class,proto3" form:"class" json:"class" query:"class"`
	Remark     *Remark               `protobuf:"bytes,13,opt,name=remark,proto3" form:"remark" json:"remark" query:"remark"`
	Options    map[string]*anypb.Any `protobuf:"bytes,14,rep,name=options,proto3" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" form:"options" json:"options" query:"options"`
	CreateTime int64                 `protobuf:"varint,15,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
	UpdateTime int64                 `protobuf:"varint,16,opt,name=updateTime,proto3" form:"updateTime" json:"updateTime" query:"updateTime"`
	DeleteTime int64                 `protobuf:"varint,17,opt,name=deleteTime,proto3" form:"deleteTime" json:"deleteTime" query:"deleteTime"`
	Role       int32                 `protobuf:"varint,18,opt,name=role,proto3" form:"role" json:"role" query:"role"`
}

func (x *UserVO) Reset() {
	*x = UserVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVO) ProtoMessage() {}

func (x *UserVO) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVO.ProtoReflect.Descriptor instead.
func (*UserVO) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserVO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserVO) GetCodeType() string {
	if x != nil {
		return x.CodeType
	}
	return ""
}

func (x *UserVO) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserVO) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserVO) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UserVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserVO) GetBirth() int64 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *UserVO) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserVO) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserVO) GetEnrollYear() int32 {
	if x != nil {
		return x.EnrollYear
	}
	return 0
}

func (x *UserVO) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *UserVO) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *UserVO) GetRemark() *Remark {
	if x != nil {
		return x.Remark
	}
	return nil
}

func (x *UserVO) GetOptions() map[string]*anypb.Any {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UserVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *UserVO) GetDeleteTime() int64 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

func (x *UserVO) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type Remark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time    int64  `protobuf:"varint,1,opt,name=time,proto3" form:"time" json:"time" query:"time"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" form:"content" json:"content" query:"content"`
}

func (x *Remark) Reset() {
	*x = Remark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Remark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remark) ProtoMessage() {}

func (x *Remark) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remark.ProtoReflect.Descriptor instead.
func (*Remark) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{1}
}

func (x *Remark) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Remark) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 注册相关
type UserSignUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserVO `protobuf:"bytes,1,opt,name=user,proto3" form:"user" json:"user" query:"user"`
}

func (x *UserSignUpReq) Reset() {
	*x = UserSignUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpReq) ProtoMessage() {}

func (x *UserSignUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpReq.ProtoReflect.Descriptor instead.
func (*UserSignUpReq) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserSignUpReq) GetUser() *UserVO {
	if x != nil {
		return x.User
	}
	return nil
}

type UserSignUpResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserVO `protobuf:"bytes,1,opt,name=user,proto3" form:"user" json:"user" query:"user"`
	Code int32   `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg  string  `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *UserSignUpResp) Reset() {
	*x = UserSignUpResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpResp) ProtoMessage() {}

func (x *UserSignUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpResp.ProtoReflect.Descriptor instead.
func (*UserSignUpResp) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserSignUpResp) GetUser() *UserVO {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserSignUpResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserSignUpResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UserSignInReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthType   int32  `protobuf:"varint,1,opt,name=authType,proto3" form:"authType" json:"authType" query:"authType"`
	AuthId     string `protobuf:"bytes,2,opt,name=authId,proto3" form:"authId" json:"authId" query:"authId"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode,proto3" form:"verifyCode" json:"verifyCode" query:"verifyCode"`
	UnitId     string `protobuf:"bytes,4,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
}

func (x *UserSignInReq) Reset() {
	*x = UserSignInReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignInReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignInReq) ProtoMessage() {}

func (x *UserSignInReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignInReq.ProtoReflect.Descriptor instead.
func (*UserSignInReq) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserSignInReq) GetAuthType() int32 {
	if x != nil {
		return x.AuthType
	}
	return 0
}

func (x *UserSignInReq) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *UserSignInReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *UserSignInReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type UserSignInResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnitId    string `protobuf:"bytes,1,opt,name=unitId,proto3" form:"unitId" json:"unitId" query:"unitId"`
	UserId    string `protobuf:"bytes,2,opt,name=userId,proto3" form:"userId" json:"userId" query:"userId"`
	CodeType  string `protobuf:"bytes,3,opt,name=codeType,proto3" form:"codeType" json:"codeType" query:"codeType"`
	CodeValue string `protobuf:"bytes,4,opt,name=codeValue,proto3" form:"codeValue" json:"codeValue" query:"codeValue"`
	Token     string `protobuf:"bytes,5,opt,name=token,proto3" form:"token" json:"token" query:"token"`
	Code      int32  `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg       string `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *UserSignInResp) Reset() {
	*x = UserSignInResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSignInResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignInResp) ProtoMessage() {}

func (x *UserSignInResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignInResp.ProtoReflect.Descriptor instead.
func (*UserSignInResp) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserSignInResp) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UserSignInResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSignInResp) GetCodeType() string {
	if x != nil {
		return x.CodeType
	}
	return ""
}

func (x *UserSignInResp) GetCodeValue() string {
	if x != nil {
		return x.CodeValue
	}
	return ""
}

func (x *UserSignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserSignInResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserSignInResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 更新信息
type UserUpdateInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserVO `protobuf:"bytes,1,opt,name=user,proto3" form:"user" json:"user" query:"user"`
}

func (x *UserUpdateInfoReq) Reset() {
	*x = UserUpdateInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdateInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateInfoReq) ProtoMessage() {}

func (x *UserUpdateInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateInfoReq.ProtoReflect.Descriptor instead.
func (*UserUpdateInfoReq) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserUpdateInfoReq) GetUser() *UserVO {
	if x != nil {
		return x.User
	}
	return nil
}

// 更新密码
type UserUpdatePasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" form:"id" json:"id" query:"id"`
	AuthType    int32  `protobuf:"varint,2,opt,name=authType,proto3" form:"authType" json:"authType" query:"authType"`
	VerifyCode  string `protobuf:"bytes,3,opt,name=verifyCode,proto3" form:"verifyCode" json:"verifyCode" query:"verifyCode"`
	NewPassword string `protobuf:"bytes,4,opt,name=newPassword,proto3" form:"newPassword" json:"newPassword" query:"newPassword"`
}

func (x *UserUpdatePasswordReq) Reset() {
	*x = UserUpdatePasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdatePasswordReq) ProtoMessage() {}

func (x *UserUpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UserUpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserUpdatePasswordReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserUpdatePasswordReq) GetAuthType() int32 {
	if x != nil {
		return x.AuthType
	}
	return 0
}

func (x *UserUpdatePasswordReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *UserUpdatePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// 获取信息
type UserGetInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" form:"userId" json:"userId" query:"userId"`
}

func (x *UserGetInfoReq) Reset() {
	*x = UserGetInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetInfoReq) ProtoMessage() {}

func (x *UserGetInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetInfoReq.ProtoReflect.Descriptor instead.
func (*UserGetInfoReq) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserGetInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserGetInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *UserVO `protobuf:"bytes,1,opt,name=user,proto3" form:"user" json:"user" query:"user"`
	Code int32   `protobuf:"varint,255,opt,name=code,proto3" form:"code" json:"code" query:"code"`
	Msg  string  `protobuf:"bytes,256,opt,name=msg,proto3" form:"msg" json:"msg" query:"msg"`
}

func (x *UserGetInfoResp) Reset() {
	*x = UserGetInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetInfoResp) ProtoMessage() {}

func (x *UserGetInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetInfoResp.ProtoReflect.Descriptor instead.
func (*UserGetInfoResp) Descriptor() ([]byte, []int) {
	return file_core_api_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserGetInfoResp) GetUser() *UserVO {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserGetInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserGetInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_core_api_user_proto protoreflect.FileDescriptor

var file_core_api_user_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x1a,
	0x16, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcb, 0x04, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x56, 0x4f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69,
	0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x72, 0x74, 0x68, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x69, 0x72, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x65,
	0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x59, 0x65, 0x61, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x59, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x12, 0x37, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0e, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x56, 0x4f, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x1a, 0x50,
	0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x36, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x35, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x56, 0x4f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x5e, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x56,
	0x4f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x7b, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x22, 0xb8, 0x01, 0x0a,
	0x0e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x6e, 0x69, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x64, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x64, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x13, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x39, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x56, 0x4f, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x85, 0x01, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e,
	0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x56, 0x4f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x13, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0xff, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x11, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x80, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2f, 0x70,
	0x73, 0x79, 0x63, 0x68, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x69,
	0x7a, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_core_api_user_proto_rawDescOnce sync.Once
	file_core_api_user_proto_rawDescData = file_core_api_user_proto_rawDesc
)

func file_core_api_user_proto_rawDescGZIP() []byte {
	file_core_api_user_proto_rawDescOnce.Do(func() {
		file_core_api_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_user_proto_rawDescData)
	})
	return file_core_api_user_proto_rawDescData
}

var file_core_api_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_core_api_user_proto_goTypes = []interface{}{
	(*UserVO)(nil),                // 0: core_api.UserVO
	(*Remark)(nil),                // 1: core_api.Remark
	(*UserSignUpReq)(nil),         // 2: core_api.UserSignUpReq
	(*UserSignUpResp)(nil),        // 3: core_api.UserSignUpResp
	(*UserSignInReq)(nil),         // 4: core_api.UserSignInReq
	(*UserSignInResp)(nil),        // 5: core_api.UserSignInResp
	(*UserUpdateInfoReq)(nil),     // 6: core_api.UserUpdateInfoReq
	(*UserUpdatePasswordReq)(nil), // 7: core_api.UserUpdatePasswordReq
	(*UserGetInfoReq)(nil),        // 8: core_api.UserGetInfoReq
	(*UserGetInfoResp)(nil),       // 9: core_api.UserGetInfoResp
	nil,                           // 10: core_api.UserVO.OptionsEntry
	(*anypb.Any)(nil),             // 11: google.protobuf.Any
}
var file_core_api_user_proto_depIdxs = []int32{
	1,  // 0: core_api.UserVO.remark:type_name -> core_api.Remark
	10, // 1: core_api.UserVO.options:type_name -> core_api.UserVO.OptionsEntry
	0,  // 2: core_api.UserSignUpReq.user:type_name -> core_api.UserVO
	0,  // 3: core_api.UserSignUpResp.user:type_name -> core_api.UserVO
	0,  // 4: core_api.UserUpdateInfoReq.user:type_name -> core_api.UserVO
	0,  // 5: core_api.UserGetInfoResp.user:type_name -> core_api.UserVO
	11, // 6: core_api.UserVO.OptionsEntry.value:type_name -> google.protobuf.Any
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func file_core_api_user_proto_init() {
	if File_core_api_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_api_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Remark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignUpResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignInReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSignInResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdateInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUpdatePasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_api_user_proto_goTypes,
		DependencyIndexes: file_core_api_user_proto_depIdxs,
		MessageInfos:      file_core_api_user_proto_msgTypes,
	}.Build()
	File_core_api_user_proto = out.File
	file_core_api_user_proto_rawDesc = nil
	file_core_api_user_proto_goTypes = nil
	file_core_api_user_proto_depIdxs = nil
}
