replicaCount: 1
image:
  repository: harbor.harbor/psych/psych-core-api
volumeMounts:
  - name: config
    mountPath: /app/etc/config.yaml
    subPath: config.yaml
  - name: stopwords
    mountPath: /app/stopwords_full.txt
    subPath: stopwords_full.txt