// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/psych-core-api/biz/application/service"
	"github.com/xh-polaris/psych-core-api/biz/conf"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/alarm"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/config"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/message"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/unit"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/user"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	confConfig, err := conf.NewConfig()
	if err != nil {
		return nil, err
	}
	authService := service.AuthService{}
	iMongoMapper := alarm.NewAlarmMongoMapper(confConfig)
	userIMongoMapper := user.NewUserMongoMapper(confConfig)
	mongoMapper := message.NewMessageMongoMapper(confConfig)
	alarmService := service.AlarmService{
		AlarmMapper:   iMongoMapper,
		UserMapper:    userIMongoMapper,
		MessageMapper: mongoMapper,
	}
	dashboardService := service.DashboardService{
		UserMapper:    userIMongoMapper,
		MessageMapper: mongoMapper,
	}
	configIMongoMapper := config.NewConfigMongoMapper(confConfig)
	configService := service.ConfigService{
		ConfigMapper: configIMongoMapper,
	}
	unitIMongoMapper := unit.NewUnitMongoMapper(confConfig)
	userService := service.UserService{
		UserMapper: userIMongoMapper,
		UnitMapper: unitIMongoMapper,
	}
	unitService := service.UnitService{
		UnitMapper: unitIMongoMapper,
		UserMapper: userIMongoMapper,
	}
	providerProvider := &Provider{
		Config:           confConfig,
		AuthService:      authService,
		AlarmService:     alarmService,
		DashboardService: dashboardService,
		ConfigService:    configService,
		UserService:      userService,
		UnitService:      unitService,
		MessageMapper:    mongoMapper,
	}
	return providerProvider, nil
}
