// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/psych-core-api/biz/infra/conf"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := conf.NewConfig()
	if err != nil {
		return nil, err
	}
	providerProvider := &Provider{
		Config: configConfig,
	}
	return providerProvider, nil
}
