// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/psych-core-api/biz/application/service"
	"github.com/xh-polaris/psych-core-api/biz/conf"
	"github.com/xh-polaris/psych-core-api/biz/domain/auth"
	"github.com/xh-polaris/psych-core-api/biz/domain/usr"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/alarm"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/config"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/conversation"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/message"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/report"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/unit"
	"github.com/xh-polaris/psych-core-api/biz/infra/mapper/user"
	"github.com/xh-polaris/psych-core-api/biz/infra/synapse"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	confConfig, err := conf.NewConfig()
	if err != nil {
		return nil, err
	}
	iMongoMapper := user.NewUserMongoMapper(confConfig)
	unitIMongoMapper := unit.NewUnitMongoMapper(confConfig)
	authDomain := &auth.AuthDomain{
		UserMapper: iMongoMapper,
		UnitMapper: unitIMongoMapper,
	}
	alarmIMongoMapper := alarm.NewAlarmMongoMapper(confConfig)
	conversationIMongoMapper := conversation.NewConversationMongoMapper(confConfig)
	reportIMongoMapper := report.NewReportMongoMapper(confConfig)
	alarmService := service.AlarmService{
		AuthDomain:         authDomain,
		AlarmMapper:        alarmIMongoMapper,
		UserMapper:         iMongoMapper,
		UnitMapper:         unitIMongoMapper,
		ConversationMapper: conversationIMongoMapper,
		ReportMapper:       reportIMongoMapper,
	}
	messageIMongoMapper := message.NewMessageMongoMapper(confConfig)
	dashboardService := service.DashboardService{
		AuthDomain:         authDomain,
		UserMapper:         iMongoMapper,
		UnitMapper:         unitIMongoMapper,
		MessageMapper:      messageIMongoMapper,
		ConversationMapper: conversationIMongoMapper,
		ReportMapper:       reportIMongoMapper,
		AlarmMapper:        alarmIMongoMapper,
	}
	configIMongoMapper := config.NewConfigMongoMapper(confConfig)
	configService := service.ConfigService{
		AuthDomain:   authDomain,
		ConfigMapper: configIMongoMapper,
	}
	client := synapse.New4b(confConfig)
	userDomainSVC := &usr.UserDomainSVC{
		UsrMapper:  iMongoMapper,
		UnitMapper: unitIMongoMapper,
		Synp4bCli:  client,
	}
	userService := service.UserService{
		UserDomain: userDomainSVC,
		UserMapper: iMongoMapper,
		UnitMapper: unitIMongoMapper,
		Synp4bCli:  client,
		AuthDomain: authDomain,
	}
	unitService := service.UnitService{
		AuthDomain:      authDomain,
		UnitMapper:      unitIMongoMapper,
		UserMapper:      iMongoMapper,
		Synapse4bClient: client,
	}
	conversationService := service.ConversationService{
		AuthDomain:         authDomain,
		MessageMapper:      messageIMongoMapper,
		ConversationMapper: conversationIMongoMapper,
	}
	providerProvider := &Provider{
		Config:              confConfig,
		AlarmService:        alarmService,
		DashboardService:    dashboardService,
		ConfigService:       configService,
		UserService:         userService,
		UnitService:         unitService,
		ConversationService: conversationService,
		MessageMapper:       messageIMongoMapper,
		ConversationMapper:  conversationIMongoMapper,
		ReportMapper:        reportIMongoMapper,
	}
	return providerProvider, nil
}
