// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat": {
            "get": {
                "responses": {}
            }
        },
        "/config/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Initialize or create service configurations (Chat, TTS, Report) for a unit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Create Config (创建配置)",
                "parameters": [
                    {
                        "description": "Configuration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.ConfigCreateOrUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status response",
                        "schema": {
                            "$ref": "#/definitions/basic.Response"
                        }
                    }
                }
            }
        },
        "/config/get_by_unit_id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve service configurations for a specific Unit ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Get Config (获取配置)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unit ID",
                        "name": "unitId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Whether to return sensitive admin-only fields (e.g., AppIDs)",
                        "name": "admin",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Configuration details",
                        "schema": {
                            "$ref": "#/definitions/core_api.ConfigGetByUnitIdResp"
                        }
                    }
                }
            }
        },
        "/config/update_info": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update existing service configurations for a unit. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Update Config (更新配置)",
                "parameters": [
                    {
                        "description": "Configuration fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.ConfigCreateOrUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status response",
                        "schema": {
                            "$ref": "#/definitions/basic.Response"
                        }
                    }
                }
            }
        },
        "/conversation/create": {
            "post": {
                "responses": {}
            }
        },
        "/conversation/get": {
            "post": {
                "responses": {}
            }
        },
        "/conversation/list": {
            "post": {
                "responses": {}
            }
        },
        "/dashboard/alarm_overview": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get statistical overview of alarm management (high risk, processed, pending).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Alarm Overview (预警概览)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unit ID to filter",
                        "name": "unitId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alarm statistics overview",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardGetAlarmOverviewResp"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid Unit ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dashboard/alarm_records": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List psychological alarm records with filtering by emotion, status, and keywords.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "List Alarm Records (预警记录列表)",
                "parameters": [
                    {
                        "description": "Filtering and pagination options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardListAlarmRecordsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated alarm records",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardListAlarmRecordsResp"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dashboard/classes": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List classes within a unit along with user and alarm counts.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "List Classes (班级列表)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unit ID",
                        "name": "unitId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Grade filter",
                        "name": "grade",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Class filter",
                        "name": "class",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Hierarchical grade/class statistics",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardListClassesResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dashboard/conversation_records": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get detailed conversation records for a specific user, including trends and details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "User Conversation Records (用户对话记录)",
                "parameters": [
                    {
                        "description": "User ID and pagination",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardUserConvRecordsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversation history and analysis",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardUserConvRecordsResp"
                        }
                    }
                }
            }
        },
        "/dashboard/get_report": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a detailed psychological analysis report for a specific conversation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get Report (获取心理报告)",
                "parameters": [
                    {
                        "description": "Conversation ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardGetReportReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detailed report content",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardGetReportResp"
                        }
                    }
                }
            }
        },
        "/dashboard/overview": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get overall dashboard statistics, including total units, users, active users, and conversation counts. Supports period comparison.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Data Overview (数据概览)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Specific Unit ID to filter. If empty, returns global admin view (if authorized).",
                        "name": "unitId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with overview data",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardGetDataOverviewResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Insufficient permissions",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dashboard/psych_trend": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get psychological risk distribution and high-frequency keywords for a unit or globally.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Psych Trend (心理趋势)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unit ID to filter",
                        "name": "unitId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Psychological risk and keyword data",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardGetPsychTrendResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dashboard/trend": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get activity and conversation trends over time, including daily active users and conversation frequency.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Data Trend (数据趋势)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Specific Unit ID to filter",
                        "name": "unitId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Trend data points",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardGetDataTrendResp"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dashboard/unit_conversation_records": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get overall conversation statistics and records for a unit. (Work in Progress)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Unit Conversation Records (单位对话记录总览)",
                "parameters": [
                    {
                        "description": "Unit ID and pagination",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardUnitConvRecordsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Unit-wide conversation overview",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardUnitConvRecordsResp"
                        }
                    }
                }
            }
        },
        "/dashboard/units": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List all units with their respective statistics (user count, risk level, etc.). Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "List Units (单位列表)",
                "responses": {
                    "200": {
                        "description": "List of units with stats",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardListUnitsResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Admin access required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dashboard/update_alarm": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update the processing status or feedback for a psychological alarm record.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Update Alarm (更新预警状态)",
                "parameters": [
                    {
                        "description": "Alarm ID and update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardUpdateAlarmReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update status response",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardUpdateAlarmResp"
                        }
                    }
                }
            }
        },
        "/dashboard/users": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List risk users within a unit with filtering and pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "List Users (用户管理列表)",
                "parameters": [
                    {
                        "description": "Filter by level, gender, keyword and pagination",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardListUsersReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated risk user list",
                        "schema": {
                            "$ref": "#/definitions/core_api.DashboardListUsersResp"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/unit/create_and_link_user": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Batch import users and automatically link them to the unit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Unit"
                ],
                "summary": "Create And Link Users (批量创建并关联用户)",
                "parameters": [
                    {
                        "description": "Batch creation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitCreateAndLinkUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Batch processing results",
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitCreateAndLinkUserResp"
                        }
                    }
                }
            }
        },
        "/unit/get_info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve details of the specified unit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Unit"
                ],
                "summary": "Get Unit Info (获取单位信息)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unit ID",
                        "name": "unitId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Unit details",
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitGetInfoResp"
                        }
                    }
                }
            }
        },
        "/unit/link_user": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Associate an existing user with this unit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Unit"
                ],
                "summary": "Link User (关联用户)",
                "parameters": [
                    {
                        "description": "Linking details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitLinkUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status response",
                        "schema": {
                            "$ref": "#/definitions/basic.Response"
                        }
                    }
                }
            }
        },
        "/unit/sign_in": {
            "post": {
                "description": "Login for unit/organization administrator accounts.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Unit"
                ],
                "summary": "Unit Sign In (单位登录)",
                "parameters": [
                    {
                        "description": "Unit admin credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitSignInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success",
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitSignInResp"
                        }
                    }
                }
            }
        },
        "/unit/sign_up": {
            "post": {
                "description": "Register a new organization/unit account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Unit"
                ],
                "summary": "Unit Sign Up (单位注册)",
                "parameters": [
                    {
                        "description": "Unit registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitSignUpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful unit registration",
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitSignUpResp"
                        }
                    }
                }
            }
        },
        "/unit/update_info": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update organizational details for a unit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Unit"
                ],
                "summary": "Update Unit Info (更新单位信息)",
                "parameters": [
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitUpdateInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status response",
                        "schema": {
                            "$ref": "#/definitions/basic.Response"
                        }
                    }
                }
            }
        },
        "/unit/update_password": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Change the login password for a unit administrator.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Unit"
                ],
                "summary": "Update Unit Password (修改单位密码)",
                "parameters": [
                    {
                        "description": "Password update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UnitUpdatePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status response",
                        "schema": {
                            "$ref": "#/definitions/basic.Response"
                        }
                    }
                }
            }
        },
        "/user/get_info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve details of the currently authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Info (获取用户信息)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target User ID",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User profile information",
                        "schema": {
                            "$ref": "#/definitions/core_api.UserGetInfoResp"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/sign_in": {
            "post": {
                "description": "Login for end-users using password or verification code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User Sign In (用户登录)",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UserSignInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success with JWT token",
                        "schema": {
                            "$ref": "#/definitions/core_api.UserSignInResp"
                        }
                    },
                    "400": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/sign_up": {
            "post": {
                "description": "Register a new end-user (e.g., student/teacher).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User Sign Up (用户注册)",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UserSignUpReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful registration response",
                        "schema": {
                            "$ref": "#/definitions/core_api.UserSignUpResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/update_info": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update profile data for the end-user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User Info (更新用户信息)",
                "parameters": [
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UserUpdateInfoReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status response",
                        "schema": {
                            "$ref": "#/definitions/basic.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/update_password": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Change the login password for an end-user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User Password (修改用户密码)",
                "parameters": [
                    {
                        "description": "Password update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core_api.UserUpdatePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status response",
                        "schema": {
                            "$ref": "#/definitions/basic.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "anypb.Any": {
            "type": "object",
            "properties": {
                "type_url": {
                    "description": "A URL/resource name that uniquely identifies the type of the serialized\nprotocol buffer message. This string must contain at least\none \"/\" character. The last segment of the URL's path must represent\nthe fully qualified name of the type (as in\n` + "`" + `path/google.protobuf.Duration` + "`" + `). The name should be in a canonical form\n(e.g., leading \".\" is not accepted).\n\nIn practice, teams usually precompile into the binary all types that they\nexpect it to use in the context of Any. However, for URLs which use the\nscheme ` + "`" + `http` + "`" + `, ` + "`" + `https` + "`" + `, or no scheme, one can optionally set up a type\nserver that maps type URLs to message definitions as follows:\n\n  - If no scheme is provided, ` + "`" + `https` + "`" + ` is assumed.\n  - An HTTP GET on the URL must yield a [google.protobuf.Type][]\n    value in binary format, or produce an error.\n  - Applications are allowed to cache lookup results based on the\n    URL, or have them precompiled into a binary to avoid any\n    lookup. Therefore, binary compatibility needs to be preserved\n    on changes to types. (Use versioned type names to manage\n    breaking changes.)\n\nNote: this functionality is not currently available in the official\nprotobuf release, and it is not used for type URLs beginning with\ntype.googleapis.com. As of May 2023, there are no widely used type server\nimplementations and no plans to implement one.\n\nSchemes other than ` + "`" + `http` + "`" + `, ` + "`" + `https` + "`" + ` (or the empty scheme) might be\nused with implementation specific semantics.",
                    "type": "string"
                },
                "value": {
                    "description": "Must be a valid serialized protocol buffer of the above specified type.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "basic.Pagination": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "nextToken": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "basic.PaginationOptions": {
            "type": "object",
            "properties": {
                "backward": {
                    "type": "boolean"
                },
                "lastToken": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                }
            }
        },
        "basic.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "core_api.AlarmRecord": {
            "type": "object",
            "properties": {
                "emotion": {
                    "description": "情绪状态",
                    "type": "string"
                },
                "id": {
                    "description": "唯一Id",
                    "type": "string"
                },
                "keywords": {
                    "description": "关键词列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lastConversationTime": {
                    "description": "上次对话时间（时间戳）",
                    "type": "integer"
                },
                "status": {
                    "description": "处理状态",
                    "type": "string"
                },
                "totalConversationRounds": {
                    "description": "总对话轮数",
                    "type": "integer"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/core_api.User"
                        }
                    ]
                }
            }
        },
        "core_api.ChatApp": {
            "type": "object",
            "properties": {
                "appId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "core_api.ClassInfo": {
            "type": "object",
            "properties": {
                "alarmNum": {
                    "type": "integer"
                },
                "class": {
                    "type": "integer"
                },
                "teacherName": {
                    "type": "string"
                },
                "teacherPhone": {
                    "type": "string"
                },
                "userNum": {
                    "type": "integer"
                }
            }
        },
        "core_api.Config": {
            "type": "object",
            "properties": {
                "chat": {
                    "$ref": "#/definitions/core_api.ChatApp"
                },
                "createTime": {
                    "type": "integer"
                },
                "report": {
                    "$ref": "#/definitions/core_api.ReportApp"
                },
                "status": {
                    "description": "active | deleted",
                    "type": "string"
                },
                "tts": {
                    "$ref": "#/definitions/core_api.TTSApp"
                },
                "type": {
                    "description": "chain | end2end",
                    "type": "string"
                },
                "unitId": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "integer"
                }
            }
        },
        "core_api.ConfigCreateOrUpdateReq": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "boolean"
                },
                "config": {
                    "$ref": "#/definitions/core_api.Config"
                }
            }
        },
        "core_api.ConfigGetByUnitIdResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "config": {
                    "$ref": "#/definitions/core_api.Config"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "core_api.ConvDetail": {
            "type": "object",
            "properties": {
                "digest": {
                    "description": "摘要",
                    "type": "string"
                },
                "keywords": {
                    "description": "关键词（词云）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/core_api.Keywords"
                        }
                    ]
                },
                "time": {
                    "description": "对话时间",
                    "type": "integer"
                }
            }
        },
        "core_api.ConversationDuration": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "minutes": {
                    "type": "integer"
                }
            }
        },
        "core_api.DashboardGetAlarmOverviewResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "pending": {
                    "description": "当前待处理数",
                    "type": "integer"
                },
                "pendingChange": {
                    "description": "对比上周待处理变化百分比",
                    "type": "number"
                },
                "processed": {
                    "description": "当前已处理数",
                    "type": "integer"
                },
                "processedChange": {
                    "description": "对比上周已处理变化百分比",
                    "type": "number"
                },
                "total": {
                    "description": "当前高风险用户总数",
                    "type": "integer"
                },
                "totalChange": {
                    "description": "对比上周总数变化百分比",
                    "type": "number"
                },
                "track": {
                    "description": "当前需追踪数",
                    "type": "integer"
                },
                "trackChange": {
                    "description": "对比上周需追踪变化百分比",
                    "type": "number"
                }
            }
        },
        "core_api.DashboardGetDataOverviewResp": {
            "type": "object",
            "properties": {
                "activeUsers": {
                    "type": "integer"
                },
                "alarmUsers": {
                    "type": "integer"
                },
                "averageTimePerConversation": {
                    "description": "minutes",
                    "type": "number"
                },
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "totalConversations": {
                    "type": "integer"
                },
                "totalUnits": {
                    "type": "integer"
                },
                "totalUsers": {
                    "type": "integer"
                },
                "weeklyIncreaseActiveUsers": {
                    "type": "integer"
                },
                "weeklyIncreaseActiveUsersRate": {
                    "type": "number"
                },
                "weeklyIncreaseAlarmUsers": {
                    "type": "integer"
                },
                "weeklyIncreaseAlarmUsersRate": {
                    "type": "number"
                },
                "weeklyIncreaseAverageTimePerConversation": {
                    "description": "minutes",
                    "type": "number"
                },
                "weeklyIncreaseAverageTimePerConversationRate": {
                    "type": "number"
                },
                "weeklyIncreaseConversations": {
                    "type": "integer"
                },
                "weeklyIncreaseConversationsRate": {
                    "type": "number"
                },
                "weeklyIncreaseUnits": {
                    "type": "integer"
                },
                "weeklyIncreaseUnitsRate": {
                    "type": "number"
                },
                "weeklyIncreaseUsers": {
                    "type": "integer"
                },
                "weeklyIncreaseUsersRate": {
                    "type": "number"
                }
            }
        },
        "core_api.DashboardGetDataTrendResp": {
            "type": "object",
            "properties": {
                "activePoints": {
                    "description": "近一周学生活跃趋势",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.TrendPoint"
                    }
                },
                "code": {
                    "type": "integer"
                },
                "conversationDurations": {
                    "description": "对话时间分布",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.ConversationDuration"
                    }
                },
                "conversationPoints": {
                    "description": "近一周对话频率趋势",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.TrendPoint"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardGetPsychTrendResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "emotionRatio": {
                    "description": "情绪分布",
                    "allOf": [
                        {
                            "$ref": "#/definitions/core_api.EmotionRatio"
                        }
                    ]
                },
                "keywords": {
                    "description": "关键词 用于词云",
                    "allOf": [
                        {
                            "$ref": "#/definitions/core_api.Keywords"
                        }
                    ]
                },
                "msg": {
                    "type": "string"
                },
                "risks": {
                    "description": "分性别的风险等级统计",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.RiskDistribution"
                    }
                }
            }
        },
        "core_api.DashboardGetReportReq": {
            "type": "object",
            "properties": {
                "ConversationId": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardGetReportResp": {
            "type": "object",
            "properties": {
                "body": {
                    "description": "详细分析内容",
                    "type": "string"
                },
                "code": {
                    "type": "integer"
                },
                "digest": {
                    "description": "对话摘要",
                    "type": "string"
                },
                "emotion": {
                    "description": "情绪状态（由模型自由生成）",
                    "type": "string"
                },
                "keywords": {
                    "description": "关键词列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "needAlarm": {
                    "description": "是否需要告警",
                    "type": "boolean"
                },
                "title": {
                    "description": "对话标题",
                    "type": "string"
                }
            }
        },
        "core_api.DashboardListAlarmRecordsReq": {
            "type": "object",
            "properties": {
                "emotion": {
                    "type": "string"
                },
                "keyword": {
                    "type": "string"
                },
                "paginationOptions": {
                    "$ref": "#/definitions/basic.PaginationOptions"
                },
                "status": {
                    "type": "string"
                },
                "unitId": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardListAlarmRecordsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/basic.Pagination"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.AlarmRecord"
                    }
                }
            }
        },
        "core_api.DashboardListClassesResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "grades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.GradeInfo"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardListUnitsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "units": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.DashboardUnit"
                    }
                }
            }
        },
        "core_api.DashboardListUsersReq": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "string"
                },
                "keyword": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "paginationOptions": {
                    "$ref": "#/definitions/basic.PaginationOptions"
                },
                "unitId": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardListUsersResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/basic.Pagination"
                },
                "riskUsers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.RiskUser"
                    }
                }
            }
        },
        "core_api.DashboardUnit": {
            "type": "object",
            "properties": {
                "averageConversationMinutes": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "property": {
                    "type": "string"
                },
                "riskUserCount": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "integer"
                },
                "userCount": {
                    "type": "integer"
                }
            }
        },
        "core_api.DashboardUnitConvRecordsReq": {
            "type": "object",
            "properties": {
                "unitId": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardUnitConvRecordsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardUpdateAlarmReq": {
            "type": "object",
            "properties": {
                "alarm": {
                    "$ref": "#/definitions/core_api.AlarmRecord"
                }
            }
        },
        "core_api.DashboardUpdateAlarmResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardUserConvRecordsReq": {
            "type": "object",
            "properties": {
                "paginationOptions": {
                    "$ref": "#/definitions/basic.PaginationOptions"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "core_api.DashboardUserConvRecordsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "convDetail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.ConvDetail"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/basic.Pagination"
                },
                "user": {
                    "$ref": "#/definitions/core_api.User"
                },
                "userConvTrend": {
                    "$ref": "#/definitions/core_api.UserConvTrend"
                }
            }
        },
        "core_api.EmotionRatio": {
            "type": "object",
            "properties": {
                "ratio": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "core_api.GradeInfo": {
            "type": "object",
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.ClassInfo"
                    }
                },
                "grade": {
                    "type": "integer"
                }
            }
        },
        "core_api.Keywords": {
            "type": "object",
            "properties": {
                "keyTotal": {
                    "type": "integer"
                },
                "keywordMap": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int32"
                    }
                }
            }
        },
        "core_api.Remark": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "core_api.ReportApp": {
            "type": "object",
            "properties": {
                "appId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "core_api.RiskDistribution": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "gender": {
                    "description": "0=all 1=male 2=female",
                    "type": "integer"
                },
                "level": {
                    "description": "0=正常 1=低危 2=中危 3=高危",
                    "type": "integer"
                }
            }
        },
        "core_api.RiskUser": {
            "type": "object",
            "properties": {
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lastConversationTime": {
                    "description": "上次对话时间（分钟时间戳）",
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "totalConversationRounds": {
                    "description": "总对话轮数",
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/core_api.User"
                }
            }
        },
        "core_api.TTSApp": {
            "type": "object",
            "properties": {
                "appId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "speaker": {
                    "type": "string"
                }
            }
        },
        "core_api.TrendPoint": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "hour": {
                    "description": "0–23",
                    "type": "integer"
                },
                "week": {
                    "description": "1=Mon ... 7=Sun",
                    "type": "integer"
                }
            }
        },
        "core_api.Unit": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "createTime": {
                    "type": "integer"
                },
                "deleteTime": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "integer"
                }
            }
        },
        "core_api.UnitCreateAndLinkUserReq": {
            "type": "object",
            "properties": {
                "codeType": {
                    "type": "string"
                },
                "unitId": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.User"
                    }
                }
            }
        },
        "core_api.UnitCreateAndLinkUserResp": {
            "type": "object",
            "properties": {
                "allCount": {
                    "type": "integer"
                },
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "skipCount": {
                    "type": "integer"
                },
                "successCount": {
                    "type": "integer"
                }
            }
        },
        "core_api.UnitGetInfoResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "unit": {
                    "$ref": "#/definitions/core_api.Unit"
                }
            }
        },
        "core_api.UnitLinkUserReq": {
            "type": "object",
            "properties": {
                "unitId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "core_api.UnitSignInReq": {
            "type": "object",
            "properties": {
                "authId": {
                    "type": "string"
                },
                "authType": {
                    "type": "integer"
                },
                "verifyCode": {
                    "type": "string"
                }
            }
        },
        "core_api.UnitSignInResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "unitId": {
                    "type": "string"
                }
            }
        },
        "core_api.UnitSignUpReq": {
            "type": "object",
            "properties": {
                "unit": {
                    "$ref": "#/definitions/core_api.Unit"
                }
            }
        },
        "core_api.UnitSignUpResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "unit": {
                    "$ref": "#/definitions/core_api.Unit"
                }
            }
        },
        "core_api.UnitUpdateInfoReq": {
            "type": "object",
            "properties": {
                "unit": {
                    "$ref": "#/definitions/core_api.Unit"
                }
            }
        },
        "core_api.UnitUpdatePasswordReq": {
            "type": "object",
            "properties": {
                "authType": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                },
                "verifyCode": {
                    "type": "string"
                }
            }
        },
        "core_api.User": {
            "type": "object",
            "properties": {
                "birth": {
                    "type": "integer"
                },
                "class": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "codeType": {
                    "type": "string"
                },
                "createTime": {
                    "type": "integer"
                },
                "deleteTime": {
                    "type": "integer"
                },
                "enrollYear": {
                    "type": "integer"
                },
                "gender": {
                    "type": "string"
                },
                "grade": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/anypb.Any"
                    }
                },
                "password": {
                    "type": "string"
                },
                "remark": {
                    "$ref": "#/definitions/core_api.Remark"
                },
                "status": {
                    "type": "string"
                },
                "unitId": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "integer"
                }
            }
        },
        "core_api.UserConvTrend": {
            "type": "object",
            "properties": {
                "trendPoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core_api.TrendPoint"
                    }
                }
            }
        },
        "core_api.UserGetInfoResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/core_api.User"
                }
            }
        },
        "core_api.UserSignInReq": {
            "type": "object",
            "properties": {
                "authId": {
                    "type": "string"
                },
                "authType": {
                    "type": "integer"
                },
                "unitId": {
                    "type": "string"
                },
                "verifyCode": {
                    "type": "string"
                }
            }
        },
        "core_api.UserSignInResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "codeType": {
                    "type": "string"
                },
                "codeValue": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "unitId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "core_api.UserSignUpReq": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/core_api.User"
                }
            }
        },
        "core_api.UserSignUpResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/core_api.User"
                }
            }
        },
        "core_api.UserUpdateInfoReq": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/core_api.User"
                }
            }
        },
        "core_api.UserUpdatePasswordReq": {
            "type": "object",
            "properties": {
                "authType": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                },
                "verifyCode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Psych Core API",
	Description:      "Psych Core API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
