// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usergetinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersigninMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardgetalarmoverviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardlistalarmusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardlistclassesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardgetdataoverviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardlistusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configgetbyunitidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configupdateinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardlistalarmrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardgetpsychtrendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardgetdatatrendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardlistunitsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitcreateandlinkuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitgetinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitlinkuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitsigninMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitsignupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitupdateinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitupdatepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersignupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userupdateinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userupdatepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboarduserconvrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardgetreportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardupdatealarmMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardunitconvrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listconversationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configgetmodelandbgimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configupdatemodelandbgimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardcreateremarkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unitgetbyuriMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminsigninMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentsigninMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createunitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _superadminsigninMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configgetcharacterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configlistvoiceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configcharacterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configcharacteraddMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configcharacterupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configcharacterdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdailymessagesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconvbydateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsingleconvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardchatreportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configaddcharacterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configdeletecharacterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configupdatecharacterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	return nil
}

func _chatMw() []app.HandlerFunc {
	return nil
}

func _openapichatcompletionMw() []app.HandlerFunc {
	return nil
}

func _psychMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _openapigeneratereportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardgetconversationmessagesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardgetconversationreportsMw() []app.HandlerFunc {
	// your code...
	return nil
}
